contentful/experience-builder

src/styles/VisualEditorRoot.css
Removes the bottom padding that is by default applied to the root element
=> style: remove padding at the bottom of editor root element [SPA-1496]

src/styles/VisualEditorRoot.css
Without padding it becomes harder to add the element to the bottom of the page
=> revert: "fix: remove padding at the bottom of editor root element in editor mode (#132)"

src/blocks/VisualEditorBlock.tsx, src/core/stylesUtils.spec.ts, src/core/stylesUtils.ts, src/index.ts
Currently, when you nest a container within a parent container that has an existing `non-container` child, the child container defaults to 0 px height.
This PR gives all containers a default fixed height of `200px`.
=> fix: default height for containers

src/blocks/ErrorBoundary.css, src/blocks/ErrorBoundary.tsx, src/blocks/ExperienceRoot.tsx, src/blocks/VisualEditorBlock.tsx, src/blocks/VisualEditorRoot.tsx, src/styles/variables.css, src/types.ts
* Catch errors happening during rendering of the experience and display them in the Canvas when operating in `editor` mode.
* Send errors to the web app if error originated from the SDK and not the imported components.
* Display informative error screen instead of blank screen when an error happens as shown below:
=> feat: add error boundary [SPA-1507]

src/blocks/EmptyEditorContainer.tsx, src/blocks/VisualEditorRoot.tsx, src/styles/EmptyContainer.css, src/styles/variables.css
Since we’re not using any CSS library but just adding global variables, we affect other UI elements in the web app when changing our CSS variables internally. Even when the SDK is not used for rendering, the CSS is registered.
We [recently changed](https://github.com/contentful/experience-builder/pull/137/files#) the `--font-size-m` variable to make the message on the empty canvas bigger. As we still used the same variable name, this affected any other place using those global Forma-36 variables as well. Since we use the same variables in the Osana cookie banner styles tag, they get overwritten by our definitions.
- Revert the value of the global variables
- Further, adjust the styles of the EmptyEditorContainer to align with the Figma designs
- Fix typo in file name
=> fix: global styles, text size in ErrorContainer, styles in EmptyContainers [SPA-1587]

packages/experience-builder-sdk/src/core/stylesUtils.spec.ts, packages/experience-builder-sdk/src/core/stylesUtils.ts
**Previous default behavior**
When a parent container has all container children, we leave the parent container's default height as 200px. The side effect of this is that if the nested container height is more than 200px, the parent doesn't expand to fit the child - which is not a great default behavior 
**After this change**
We fit the content if a parent container has children, regardless of whether it's container or non-container children.
=> fix: container default sizing height to fit all children []

packages/experience-builder-sdk/src/blocks/VisualEditorContext.tsx, packages/experience-builder-sdk/src/hooks/useSelectedInstanceCoordinates.ts, packages/experience-builder-types/src/constants.ts
The canvas interaction tooltip was jumping around to previous selected components when scrolling the page. It turns out this was due to the onScroll listener being registered multiple times - one for each time the selected node changed.
In order to avoid this I am switching the selected node to be Ref which won't trigger the useEffect to rerun on change, but it will still have the latest value when the listener runs.
See also this SO question: https://stackoverflow.com/questions/55565444/how-to-register-event-with-useeffect-hooks
https://github.com/contentful/experience-builder/assets/2773012/2ba384d5-ed1a-4dc8-b6c3-adf023dba865
https://github.com/contentful/experience-builder/assets/2773012/a1673f8f-25de-4715-911a-3df6ab916872
=> Fix: selected component jumps around on scroll [ALT-62]

packages/experience-builder-sdk/src/core/EntityStore.spec.ts, packages/experience-builder-sdk/src/core/EntityStore.ts
Once migrating our gatsby project to SSG, I noticed failed builds, where a `url` prop of an `Image` component received the following:
```tsx
{
url: "//images.ctfassets.net/fo9twyrwpveg/20xNXuZXY4wPsT3drodPvG/5d98ed2b7dd2da55def5862dc4b2444c/illu_3__1_.svg",
details: { size: 34927, image: { width: 80, height: 80 } },
fileName: "illu 3 (1).svg",
contentType: "image/svg+xml"
}
```
Instead of a plain string.
So I investigated and found out that in preview and delivery mode, we [are calling `getValue` function](https://github.com/contentful/experience-builder/blob/main/packages/experience-builder-sdk/src/blocks/CompositionBlock.tsx#L62) of the entityStore, which is defined in base class and doesn't have the [fallback for handling bound …
=> fix: correctly retrieve the url from the bound asset in preview/delivery []

packages/experience-builder-sdk/src/styles/EmptyContainer.css
Minor font color change to the Empty Container.
Before:
After:
=> fix: minor change to empty container font color [ALT-59]

packages/experience-builder-sdk/src/styles/EmptyContainer.css
Minor change to apply the highlight styles when a dragged component is hovering over the Empty Container, to give visual feedback to the user that the component can be dropped/inserted.
(Previously the blue highlight styles were shown when a component is active/dragged)
Dragged component not hovering:
Dragged component is hovering:
=> fix: empty container highlight on hover [ALT-60]

packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/vite.config.ts, yarn.lock
Currently, React is included in the production build, which could cause issues and increases the size of the built bundle. This update adds the rollup-plugin-peer-deps-external package and updates the Vite config to use it. This will exclude any external libraries marked as external peer deps. This drops the bundle size from 167KB to 89KB.
=> fix(experience-builder-sdk): update rollup config to not include react in build []

packages/experience-builder-sdk/src/index.ts, packages/experience-builder-sdk/src/types.ts
Exports the ExternalSDKMode from the main types entry point. This appeared to be accidentally missing.
=> fix(experience-builder-sdk): export ExternalSDKMode type []

packages/experience-builder-types/src/types.ts
Support unbound and bound values in variable definitions types
=> chore: support unbound and bound values in variable definitions [SPA-1639]

packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/editor/designComponentUtils.ts, packages/experience-builder-sdk/src/utils/validation.ts
1. Don't pass any custom `props` to the rendered `div` as it will basically render HTML attributes like `text_randomUUID=[ Object object ]`
2. When the visual SDK receives the `REQUESTED_ENTITIES`, don't log a warning about an unexpected message.
How the DOM looked before this PR:
=> fix: dont show warning about alien message, don't render invalid attributes []

packages/experience-builder-sdk/src/core/designTokenRegistry.ts, packages/experience-builder-sdk/src/index.ts, packages/experience-builder-types/src/constants.ts, packages/experience-builder-types/src/types.ts
This PR allows the user to define their layoutDefinition for the layout sidebar as follows below.
Here's the user_interface associated PR that shows the UI and the mechanics of how it would work https://github.com/contentful/user_interface/pull/18533
```
export const buttonDefinition: ComponentDefinition = {
id: 'ryuns-button',
name: 'ryuns-button',
category: 'buttons',
**designTokensDefinition: {
spacing: { XS: '0px', S: '16px', M: '32px', L: '64px' },
},**
// thumbnailUrl: string | undefined;
variables: {
buttonTitle: {
type: 'Text',
displayName: 'Button Title',
defaultValue: 'Click Me'
},
marginValues: {
type: 'Text',
displayName: 'Margin Values',
defaultValue: ['0px', '16px', '32px', '64px']
}
},
builtInStyles: ["cfHorizontalAlignment", "cfVerticalAlignment", "cfMargin", "cfPadding", …
```
=> [ALT-148] Allows user defined styling layout through Component Definition injection at the root level

packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/core/componentRegistry.test.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/core/preview/EntityStore.ts, packages/experience-builder-sdk/src/utils/withComponentWrapper.spec.tsx, packages/experience-builder-sdk/src/utils/withComponentWrapper.tsx, packages/experience-builder-types/src/types.ts, yarn.lock
This change registers five basic components from `@contentful/experience-builder-components`
* Image
* Button
* Heading
* Text
* RichText
These five components and any components that the customer app registers with the SDK will now be wrapped in a container by default using the `withContainerWrapper` util.
The customer can use the ComponentRegistration options to change the behavior of the container wrapper.
* wrapComponent - `true` (default) wraps component in a container element and `false` can be used to opt-out and skip using a container wrapper
* wrapContainerTag - `'div'` (default) uses a \<div\> for the wrapper and other element types can be used like `'span'` if needed
This is potentially a breaking change (rendering the container wrapper by default for registered components) and …
=> feat!: register toolkit components and include wrap container by default [ALT-115]

packages/experience-builder-types/src/types.ts
This is needed because of how we want to represent borders for design token since they consist of the name, size, and color. Basically it's the same [name] -> [value] convention except the value in this case has multiple values, thus requires to be represented by an object.
```
border: {
"Hero": { size: '2px', color: "#ff0000", },
"Card": { size: '4px', color: "#00ff00", }
}
```
=> refactor: generalize the DesignTokenDefinition type [ALT-137]

packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.test.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.spec.tsx, packages/experience-builder-sdk/src/core/editor/designComponentUtils.spec.ts, packages/experience-builder-sdk/src/core/editor/designComponentUtils.ts, packages/experience-builder-sdk/src/core/preview/designComponentUtils.spec.ts, packages/experience-builder-sdk/test/__fixtures__/composition.ts, packages/experience-builder-sdk/test/__fixtures__/designComponent.ts
As shown here in [this Miro board](https://miro.com/app/board/uXjVNL-mFho=/?moveToWidget=3458764570954909785&cot=14), we want to replace the component value pointers with the actual unbound value or bound value. We now replace those correctly, so in the final rendering we don't have to handle `ComponentValue` anymore.
=> fix: replace component values with actual onces before rendering []

packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/designTokenRegistry.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.spec.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, yarn.lock
Only do this for margin and padding so we can first agree on the implementation structure and then once agreed we can apply it for all other tokens like direction, background color, border.
Additionally, the strategy is as follows
Use a set to determine which potential variables (cfMargin, cfPadding) could have template strings
If the variable is one of those types which could have a template string, run through a specific parser that will know how to handle the given type in the `designTokenRegistry` file. This way we can map specific parsers to specific variable types which may share or differ in their structure. Therefore as we add a new variable type (ie. border in a separate PR) we can refactor this code to generalize as we go along
Stores the design token key instead of the hard …
=> feat: resolves the design token values [ALT-171]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.spec.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/EntityStore.ts, packages/experience-builder-sdk/src/core/preview/designComponentUtils.ts
Apply the same changes as in https://github.com/contentful/experience-builder/pull/192 but for preview mode where we have a different structure (the raw data format).
Also, the function `EntityStore.getValue` renders warnings when it receives full entities instead of links. The links are already resolved by default through our APIs, thus the logic needs to be aware of both cases.
=> fix: render component values in preview and resolve links properly []

packages/experience-builder-sdk/src/ExperienceRoot.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorRoot.tsx, packages/experience-builder-sdk/src/core/editor/EditorModeEntityStore.ts, packages/experience-builder-sdk/src/utils/validation.ts
During the first initialization phase, the entity store is switching often between a "filled" and an "empty" state. When we're unlucky, somewhere in between it tries to render design component blocks but they are not yet in the entity store as it was emptied again. As a result, we see this warning everytime in the console and in some scenarios, the component is not rendered at all (e,g, colorful coin demo):
> `Entry for design component with ID '${componentId}' not found`
The SDK will always start in non-editor mode and already load the entities in the preview entity store. After it switches to editor mode, it won't set the list of entities to `[]` but to `previousEntityStore?.entities` to eventually reuse already loaded entities.
We have an effect that should re-initialize the entity …
=> feat: initialise entity store sustainably in editor mode [SPA-1711]

packages/core/rollup.config.mjs, packages/core/src/exports.ts, packages/core/src/types.ts, packages/core/tsconfig.json
This PR fixes a typings bug. Before, the typings would export code that would include the internal paths imports (IE: `import { blah } from '@types'. These should be resolved to their relative paths, which this PR fixes.
=> chore(core): fix typings issue

packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/communication/sendMessage.ts, packages/experience-builder-sdk/src/core/editor/EditorModeEntityStore.ts
Currently, the entity store is sometimes not holding the entries for design components. It looks like a race condition that only happens on a hosted SDK, so we need to ship this via new version to our demo project and deploy it to better understand why the entity store is empty when rendering design components.
=> feat: improve logs and add more debug logs to understand the entity store issues [SPA-1711]

packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.test.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/core/editor/EditorModeEntityStore.ts
The initial value of `useRef` is only accepted on the first render. However, this value is still calculated on every render cycle. So we create a new entity store on every render cycle.
I'm not sure if this caused the seen side effects of race conditions in the colorful coin demo. Still, it is very likely a bigger memory leak and can eventually have side effects as it registers subscribers to the message protocol each time.
By having this as a state variable, we integrate the initialization better into Reacts render cycle as the value is guaranteed to be defined on each render but also we don't regenerate it when not necessary as it's protected through the setter method.
=> fix: dont initialise entity store on every render by using state [SPA-1711]

packages/experience-builder-sdk/src/core/designTokenRegistry.ts
=> fix: design token logic breaks auto height for empty containers []

packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/core/designTokenRegistry.ts, packages/experience-builder-sdk/src/core/editor/EditorModeEntityStore.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts
I discovered a few flaws that might end up in the design components and content not loading at all initially. I implements some small tweaks that are likely to fix this :)
In some cases, we already have a pre-filled entity store. This happens sometimes as we start in preview mode and then switch over to editor mode taking over the already-fetched entities. It also happens when using hot reloading.
In those cases, we should try to render the tree which we currently block via the boolean `areEntitiesFetched`.
To not silently just render nothing, we now try to render from the beginning on by setting `areEntitiesFetched` to true initially.
Also, we only update this variable only and only if we are really fetching something. The editor entity store is not returning either a boolean or a …
=> fix: switching locale makes design components disappear [SPA-1711]

package-lock.json, packages/components/src/components/Text/Text.css, packages/components/src/components/Text/index.ts, packages/components/styles.css, packages/core/src/definitions/styles.ts, packages/experience-builder-sdk/src/core/definitions/variables.ts
* Updated the font weight style definition to include `validations` values that are used as select options in the UI
* Removed css from `.cf-text` for the Text component to use all built-in typography style controls
=> fix: update font weight validations

packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/ExperienceRoot.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.test.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorRoot.tsx, packages/experience-builder-sdk/src/core/editor/EditorModeEntityStore.ts, packages/experience-builder-types/package.json, yarn.lock
The current fetching logic for initial entities (data source and design components) was sometimes not fetching entities correctly and failed thereby to render. While we identified the root cause of the user interface being too slow for the initial fetching, this PR is adding more transparency to this process by adding debug, warning, and error logs in unexpected cases.
The biggest logical change in this PR is the function `fetchMissingEntities` which is basically the previous effect but in a new callback. This function is now also imperatively called when we receive the design components. I added this as design components are not part of the React state and thus won't cause a re-rendering solely through this change. To avoid possible race conditions related to this, we're explicitly …
=> fix: improve initial fetching mechanism [SPA-1711]

packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.test.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorBlock.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/blocks/editor/VisualEditorRoot.tsx, packages/experience-builder-sdk/src/core/editor/designComponentUtils.ts
With my previous PR, the SDK did only fetch once which caused rendering issues as nto all entities might have been requested yet.
Now, we're checking the entityStore and update it everytime the data source or design components change (via componentTreeUpdated)
=> fix: refetch when dataSource or design components changed [SPA-1711]

packages/core/src/registries/designTokenRegistry.ts, packages/core/src/utils/breakpoints.ts
Prevent errors like the one below when design tokens are removed after an experience was saved/published with a design token selected.
I updated `resolveSimpleDesignToken` to use the the default values from `builtInStyles` or `optionalBuiltInStyles` as a fallback value if available, since that would provide a better value to use as the fallback that can vary based on the variable.
=> fix(core): add design token fallback values based on default values [ALT-200]

packages/core/src/entity/EditorModeEntityStore.ts, packages/visual-editor/src/hooks/useComponentProps.tsx
When selecting an asset with a newly added file, the SDK sometimes has some kind of hick-up - not sure why exactly. As a result, it throws an error that it is unable to read property `linkType` of undefined. To avoid these unexpected issues, I added some safety checks if `sys` is even existing in the related places.
https://github.com/contentful/experience-builder/assets/9327071/37fadf02-6705-4683-8af1-2140190bdc2a
=> fix: handle missing linkType property [SPA-1762]

packages/core/src/definitions/styles.ts, packages/core/src/registries/designTokenRegistry.ts
Changing the default border style to 0px width and white to align with the default background color.
Without design tokens defined:
With design tokens:
=> fix: change default border style color to 0px width []

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/visual-editor/src/hooks/useComponent.tsx
Reverts contentful/experience-builder#231
Currently, the rendering of assemblies is broken. To remove this critical bug, we will just revert this fix for now.
=> fix(visual-editor): render assembly nodes by passing the required props [ALT-255]

packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts
Changes
* Enable design tokens for text color styling
* Rename `border` and `color` tokens to singular for consistency
=> fix(core): enable design tokens for text color style [ALT-249]

packages/experience-builder-sdk/README.md
Readme revisions for design tokens.
Design Tokens are introduced at the bottom of the Wiki Home page:
* https://github.com/contentful/experience-builder/wiki#registering-design-tokens
Design Token Definitions are more thoroughly described in the Design Tokens dedicated Wiki page:
* https://github.com/contentful/experience-builder/wiki/Design-Tokens#design-tokens-definition
=> chore(experience-builder-sdk): update readme [ALT-250]

packages/visual-editor/src/components/Dropzone/styles.module.css, packages/visual-editor/src/components/EmptyContainer/EmptyContainer.module.css, packages/visual-editor/src/components/EmptyContainer/EmptyContainer.tsx, packages/visual-editor/src/global.css, packages/visual-editor/src/hooks/usePlaceholderStyle.ts
Changes
* For [ALT-273](https://contentful.atlassian.net/browse/ALT-273): outline width increased from 1px to 2px
* For [ALT-275](https://contentful.atlassian.net/browse/ALT-275): updated colors of some component outlines and dropzone backgrounds (changes made in coordination with Travis on Zoom)
[ALT-273]: https://contentful.atlassian.net/browse/ALT-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALT-275]: https://contentful.atlassian.net/browse/ALT-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(visual-editor): change component outlines and dropzone backgrounds [ALT-273] [ALT-275]

packages/core/src/constants.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts
We figured out that changing the payload of the iframe message can't just be addressed by a renaming with supporting old and new event type. The previous renaming leads to breaking changes for the SDK which we want to avoid.
For a smoother SDK migration time, we should instead use only the new event shape in the newer SDK and only support the older event shape in the older SDK (<=4.0.0-alpha.10).
To support both ways, the web app will send old and new events through the message channel until we drop the support for the deprecated functions.
TLDR; how the migration will work:
- Old SDK accepts only designComponentsAdded/ designComponentsRegistered (with param `designComponents`)
- New SDK accepts only assembliesAdded/ assembliesRegistered (with param `assemblies`)
- Experience Builder will …
=> fix(experience-builder): only accept new assembly event [SPA-1730]

packages/visual-editor/src/hooks/usePlaceholderStyle.ts
Fixes: https://contentful.atlassian.net/browse/ALT-282
The white gap between containers is a 50px margin-top set on the green container.  With these changes, this 50px margin-top is included in the `clientY` computation so the dropzone renders in the correct place.
=> fix: update dropzone to consider children margins [ALT-282]

packages/components/src/components/ContentfulContainer/ContentfulContainerAsHyperlink.tsx, packages/experience-builder-sdk/src/components/ContentfulContainerAsHyperlink.tsx, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/src/store/tree.ts, packages/visual-editor/src/types/treeActions.ts, packages/visual-editor/src/utils/getTreeDiff.ts, packages/visual-editor/src/utils/treeHelpers.ts
When creating a new assembly out of an existing container, the tree diff logic was making two mistakes:
- It detected not only the "replace" action but also the "remove" action which led to not rendering the new node at all
- The replace action itself did not replace the node fully which caused a weird mix of the original block node and new assembly node with warning logs and missing designs for the container inside the new assembly node.
I addressed the first problem by explicitly handling this case. The second one I could resolve by capturing the index of the node that should be replaced. I could then replace the node as a whole via its parent and the index.
=> fix: replace node completely with new assembly node [SPA-1775]

packages/visual-editor/src/components/Draggable/DraggableComponent.tsx, packages/visual-editor/src/components/Draggable/styles.module.css, packages/visual-editor/src/components/Dropzone/EditorBlock.tsx, packages/visual-editor/src/global.css
https://contentful.atlassian.net/browse/ALT-260
https://github.com/contentful/experience-builder/assets/8539634/d5580dc8-2ffd-4d18-a6fc-68b73df024dc
=> fix: show outline when hovering over readonly assembly blocks [ALT-260]

package-lock.json, packages/core/package.json, packages/core/src/utils/utils.spec.ts, packages/core/src/utils/utils.ts
We were getting some weird lodash import errors in user interface when the core dep was referenced locally. We were using only two relatively simple methods from lodash (times and random), so I replaced those with custom ones and removed the package. This helped fix the error we were seeing.
=> fix(core): remove lodash dep to get rid of weird reference errors

packages/visual-editor/src/components/RootRenderer/DNDProvider.tsx, packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx, packages/visual-editor/src/components/VisualEditorRoot.tsx
Adding a div with event handlers allowed to skip the "native" dnd and simulate events in cypress.
All that is required is setting the `window.Cypress` property.
You can see the progress on the video below. Sorry for the music - I forgot to disable mic when recording.
https://github.com/contentful/experience-builder/assets/4171202/67f92c5f-e2ce-4eaa-a9c9-06e3210b4c33
=> fix: add dnd cypress stub [SPA-1712]

package.json
There was a prepublish script that called 'lerna run build' that was causing the monorepo to do a build after npm install. This seems unnecessary and is causing the CI pipeline to slow down because there are multiple unneeded builds happening.
=> chore: remove erroneous prepublish script from main package file

packages/core/src/utils/utils.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/index.ts
Enrich the core and SDK module by putting `checkIsAssemblyNode` and `checkIsAssemblyDefinition` into the utils. Also deprecated `checkIsAssembly` as this naming will be confusing when talking about the different entities around assemblies.
=> style: move all assembly checks to core utils []

package-lock.json, packages/visual-editor/src/components/Dropzone/Dropzone.tsx
Main light bulb idea was to treat existing components on the canvas more like dragging components from the component-list.
This PR allows all components to be dragged across parents however it lacks one feature (which might even be debatable if we want this or not).
The feature it lacks is the ability to create new containers as you're dragging the component.
=> fix: allows re-parenting of components, however does not allow for new containers to be created while dragging across parents

packages/visual-editor/src/utils/getTreeDiff.ts, packages/visual-editor/src/utils/treeHelpers.ts
When detaching an assembly node, the tree-diffing logic did not recognize that this was technically a "replacement". Based on the total node count in the tree it always figured that a node was "added" and thus didn't remove the previous assembly node but just added the new detached container.
I tested multiple ways of adding, removing, re-ordering, and replacing nodes to ensure that this had no side-effects on other rendering scenarios.
=> fix: duplicate assembly rendering [SPA-1783]

catalog-info.yml, packages/experience-builder-sdk/catalog-info.yml
To show this mono repo as well as the SDK in Roadie, we need to provide catalog info configurations. Those are by no mean perfect. I looked at similar repositories to define at least the minimal required attributes.
=> chore: add catalog info for backstage integration [SPA-1497]

packages/visual-editor/src/components/Draggable/canvasToolsUtils.ts, packages/visual-editor/src/components/Draggable/styles.module.css
Make the hover labels match more closely with the active labels in terms of height and width. Kept the gray500 color because the color scheming will be handled during the dark mode ticket.
=> fix: update hover labels to be more like onclick labels

packages/components/src/utils/constants.ts
We're seeing security warnings and suspect the thumbnail URLs which use an insecure protocol.
=> fix: use https protocol for component thumnails []

.github/dependabot.yml, .github/workflows/auto-merge.yml, .github/workflows/main.yml
For security purposes, we should not use old outdated versions of packages. To get recent security patches and bugfixes, we add dependabot to this mono repo.
I added a simple config that supports the npm and github registry. It will execute every week and auto-merge releases into the `development` branch. Those commits don't trigger an automatic version release, so we can ensure to not break the SDK.
=> chore: introduce dependabot without release automation [SPA-1497]

.github/workflows/main.yml
The dependabot automation is working but it triggers dev prereleases:
https://github.com/contentful/experience-builder/actions/runs/7712599014/job/21020767544
Turns out that we have a different bot name `contentful-automation[bot]` that we need to exclude here as well.
=> chore: ignore cf automation bot as well for publishing [SPA-1497]

packages/components/src/components/Assembly/Assembly.tsx, packages/components/src/components/Columns/Columns.tsx, packages/components/src/components/Columns/SingleColumn.tsx, packages/components/src/components/ContentfulContainer/ContentfulContainer.tsx, packages/components/src/components/ContentfulContainer/ContentfulContainerAsHyperlink.tsx
In #296 the `[data-cf-node-*]` attributes moved from the `componentProps` to the `wrapperProps`.
This change removes these attributes from some components to prevent them from appearing twice -- on the component and the editor wrapper (draggable) element
=> fix(components): remove [data-cf-node-*] attributes from components []

.github/workflows/auto-merge.yml
Major version upgrades could introduce breaking changes or bring unwanted features that should be reviewed manually by a dev before merging those.
=> chore: dont auto merge major version upgrades [SPA-1496]

packages/components/src/components/RichText/RichText.css, packages/components/src/components/RichText/index.ts, packages/components/src/styles.ts, packages/experience-builder-sdk/src/core/componentRegistry.ts
Rich Text now has the following design options as shown in the screenshots
=> feat: updates rich text component definition to hold default stylings rather than using css modules [ALT-311]

packages/components/src/components/ContentfulContainer/ContentfulContainer.css, packages/components/src/components/ContentfulContainer/ContentfulContainer.tsx
Adds background label to the Container and Section component.
Also cuts the Container label short on either end if the container itself has too small of a width
Container label no longer shows up when it's non-empty
=> Container and Section labels [ALT-355]

packages/core/src/utils/breakpoints.ts, packages/visual-editor/src/hooks/useBreakpoints.ts
There were at least two bugs when having breakpoint-specific styles:
When opening the experience builder, we used to render the mobile value first. There were two problems related to that:
The "matches" state variable is an empty object initially. It is a state variable that receives the `initialMediaQueryMatches` only once. Though, on the first run the breakpoint definitions are not yet defined, so the initial value becomes `{}`.
**Solution**: Fill the state variable ones in the effect and trigger the effect only when the breakpoint definitions changed.
Now when the "matches" variable is `{}`, the util function just assumes `true` for every breakpoint. Due to the specificity priority for desktop-first, we ended up assuming we're on mobile.
**Solution:** We only assume `true` for the …
=> fix(experience-builder): rendering breakpoint-specific design values [SPA-1772]

package-lock.json, packages/core/src/definitions/styles.ts, packages/core/src/types.ts
This new `cfWrapColumnsCount` design value allows us to track how many columns there should be before wrapping to a new row for the columns component.
Demo of wrapAfter is available in the related user_interface PR: https://github.com/contentful/user_interface/pull/19524
=> feat(components): add new design value to track column wrap [ALT-278]

.eslintrc.cjs, README.md, packages/components/package.json, packages/components/rollup.config.mjs, packages/core/package.json, packages/core/rollup.config.mjs, packages/create-experience-builder/package.json, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/rollup.config.mjs, packages/storybook-addon/package.json, packages/test-app/package.json, packages/visual-editor/package.json, packages/visual-editor/rollup.config.mjs
A recent change to add the tsconfig 'noEmitOnError' config value caused the rollup watch server to hault when there was any type of compilation error.
This PR adds new "dev" scripts to each of main EB packages to fire up the rollup watch server with a dev mode argument, which will disable the 'noEmitOnError' option, allowing the process to still report the error but continue running. 
When building the application (npm run build), the 'noEmitOnError' option will still be used and will error out if there is a compilation error.
To use the new scripts, go into the packages folder, and run 'npm run dev', which will build the application and then continually watch for file changes, which will retrigger a build.
=> chore: add dev scripts for local development

packages/core/src/constants.ts, packages/core/src/definitions/styles.ts, packages/core/src/types.ts
This new variable allows us to lock a column span so that during column resizing, a locked column keeps it's span value instead of dynamically changing.
user_interface PR: https://github.com/contentful/user_interface/pull/19566
Also updated label from `Single Column` to `Column` per Travis' request
=> feat(components): ability to lock a column span for columns component

packages/visual-editor/src/hooks/useEditorSubscriber.ts
Properly remove event listener on scroll
We had the capture option true when adding the event listener, but never specified on remove that the event listener to be removed is registered as a capturing event listener.
Before PR
https://github.com/contentful/experience-builder/assets/30434146/4abf57e1-916b-470e-9653-f81781ae6eba
After PR
https://github.com/contentful/experience-builder/assets/30434146/c8ae529c-96b9-4e26-b89c-1d0797d934b8
=> fix: properly remove event listener on scroll [ALT-395] [SPA-1817]

packages/core/src/__fixtures__/breakpoints.ts, packages/core/src/utils/breakpoint.spec.ts, packages/core/src/utils/breakpoints.ts
When setting up a bg color for desktop and tablet but not mobile, the mobile view would show the styles set up for desktop.
<details><summary>Bug Recording</summary>
<p>
https://github.com/contentful/experience-builder/assets/9327071/813b8d24-a8e5-4806-ae84-2f57d8ff65c4
</p>
</details> 
The design token logic directly fall back to desktop if mobile was not defined (for token-enabled props). This solution is now adjusted to consider the breakpoint cascading rules.
<details><summary>Solution Recording</summary>
<p>
https://github.com/contentful/experience-builder/assets/9327071/8ac60ba0-495b-48a4-adf6-878d1d378a6b
</p>
</details>
=> fix: mobile falls back to tablet style for token-enabled props [SPA-1772]

packages/components/package.json, packages/core/package.json, packages/create-experience-builder/package.json, packages/experience-builder-sdk/package.json, packages/storybook-addon/package.json, packages/visual-editor/package.json
In the web app, I'm not able to pull any version of `core` that was released in the last week. As we moved all private packages to `npm.pkg.github.com`, it looks like we need to move or public ones as well. According to the [docs](https://docs.npmjs.com/cli/v8/using-npm/registry#description), `.npmrc` does only allow defining a registry per namespace. In the user interface, we point the whole Contentful namespace to `npm.pkg.github.com` which forces us to move experience-builder to this registry as well.
I hope that mirroring works correctly so that customers can still install via the npm registry. We already have a similar config for almost all our customer-facing packages - see [code search](https://github.com/search?type=code&auto_enroll=true&q=org%3Acontentful+publishConfig+language%3A …
=> chore: publish packages to github npm registry []

packages/components/src/components/Heading/Heading.css, packages/components/src/components/Heading/Heading.tsx, packages/components/src/components/RichText/RichText.css, packages/components/src/components/RichText/RichText.tsx, packages/components/src/components/Text/Text.css, packages/components/src/components/Text/Text.tsx, packages/components/src/styles.ts
Add css properties so text components respect line breaks
=> fix(components): line breaks for text built-ins [ALT-307]

packages/core/src/definitions/styles.ts
This changes **All Components** default Height value to `'fit-content'` instead of `'fill'`. 
I tested all structure and built-in components and this gives the expected result for all our components.
This change makes it so nested structure components will match the height of their children elements, instead of filling out (or growing) to the height of a parent structure.
=> fix: set default height to fit-content [ALT-448]

packages/core/src/entity/EntityStore.ts, packages/core/src/fetchers/createExperience.ts, packages/core/src/fetchers/index.ts, packages/core/src/utils/transformers.ts, packages/experience-builder-sdk/src/hooks/useDetectEditorMode.tsx, packages/experience-builder-sdk/src/hooks/useFetchById.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.ts, packages/experience-builder-sdk/src/index.ts
This PR fixes some issues and introduces a workaround to get SSR working in NextJS projects that use the pages router (app router is still not supported in SSR).
There were a couple of issues to tackle here.
1) The Experience that gets returned from the fetchBy{slug/id} methods returned an EntityStore object that cannot be serialized by NextJS in `getServerSideProps` due to their strict JSON serialization rules (see [here](https://github.com/vercel/next.js/issues/11993)). In order to get around this, we need to serialize the experience ourselves in getServerSideProps and then reconstruct the object back into a proper class in the component. To do the later, I reintroduced the `createExperience` function back into userland. It now takes an overloaded parameter of a json package, and if …
=> fix(experience-builder-sdk): support ssr in nextjs pages router

packages/core/src/entity/EntityStore.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.spec.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/blocks/preview/DeprecatedPreviewDeliveryRoot.tsx, packages/experience-builder-sdk/src/blocks/preview/PreviewDeliveryRoot.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts
When creating a new pattern out of a container, the custom unbound values would be persisted correctly and rendered in the editor. However, in preview mode, it would only render the default value.
This as our logic puts all unbound values from experience and assembly definitions in a single entity store. If the keys are the same, the assembly ones override the experience ones. As the former one contains only default values while the latter ones contains actual instance values, I changed the order in which we merge both maps. I added a comment to it as well in case, future us is wondering why.
Also, I realized that we have some fallbacks like `entityStore?.unboundValues ?? unboundValues` which were not necessary. This is a leftover from the merged preview/ editor rendering. Now we only …
=> fix: handle colliding unbound value keys correctly in entity store [SPA-1836]

packages/core/src/types.ts, packages/core/src/utils/transformers.ts, packages/storybook-addon/src/components/StyleSectionComponents/BorderInput/useBorderConstituents.ts, packages/storybook-addon/src/components/StyleSectionComponents/constants.ts
Instead of Inside/Outside, change it to solid, dashed, and dotted options for borders
=> fix: change inside and outside option to dashed, dotted, and solid for border options

packages/components/src/components/Columns/Columns.css, packages/components/src/components/ContentfulContainer/ContentfulContainer.css
Use zindex to always show the display labels for structural components unless the component has a child
=> Structure component labels are displayed with any background component [ALT-466]

packages/core/src/types.ts, packages/validators/package.json, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/types.ts, packages/validators/test/v2023_09_28/componentSettings.spec.ts
* Export individual types for each property value type in order to avoid using generic type.
* Align ExperienceComponentSettings['variableDefinitions'] with `ComponentDefinitionVariable` types
=> fix: export individual types for each property value type []

packages/components/src/components/Columns/Columns.css, packages/components/src/components/ContentfulContainer/ContentfulContainer.css, packages/core/src/types.ts, packages/core/src/utils/transformers.ts, packages/storybook-addon/src/components/StyleSectionComponents/BorderInput/useBorderConstituents.ts, packages/storybook-addon/src/components/StyleSectionComponents/constants.ts, packages/validators/package.json, packages/validators/src/index.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/types.ts, packages/validators/test/v2023_09_28/componentSettings.spec.ts
* fix: change inside and outside option to dashed, dotted, and solid for border options #375
* Structure component labels are displayed with any background component [ALT-466] #378
* fix: export main validator function #380
* fix: export individual types for each property value type [] #381
[ALT-466]: https://contentful.atlassian.net/browse/ALT-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release@next

package-lock.json, packages/components/README.md, packages/components/package.json, packages/components/src/components/Button/README.md, packages/components/src/components/Heading/README.md, packages/components/src/components/Image/README.md, packages/components/src/components/RichText/README.md, packages/components/src/components/Text/README.md, packages/create-experience-builder/src/fsClient.ts, packages/create-experience-builder/templates/react-vite-ts/src/App.tsx, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/storybook-addon/package.json, packages/test-app/package.json, packages/test-app/src/Page.tsx, packages/test-app/src/stories/Button.stories.ts, packages/visual-editor/package.json, packages/visual-editor/src/components/Dropzone/useComponent.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts
Rename experience builder sdk packages based on https://contentful.atlassian.net/wiki/spaces/PROD/pages/4480499829/Experience+Builder+package+rename+proposal
This PR in particular converts experience-builder-builder to experiences-components-react.
Create feature branch called experience-release based on the development branch.
Ignored the `CHANGELOG.md` and `package-lock.json` files as those should be auto regenerated
=> refactor: rename experience-builder-components to experiences-components-react [ALT-395]

package-lock.json, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/rollup.config.mjs
I noticed that core was being bundled into the SDK package, which is causing the SDK to be bigger than necessary and the core dep to be not used. This fix uses a package that automatically excludes any packages in dependencies, peer dependencies, and node apis from being packaged into the bundle.
=> chore: dont bundle core into sdk

package-lock.json, packages/components/.storybook/main.ts, packages/storybook-addon/README.md, packages/storybook-addon/package.json, packages/test-app/.storybook/main.ts, packages/test-app/package.json
Rename experience builder sdk packages based on https://contentful.atlassian.net/wiki/spaces/PROD/pages/4480499829/Experience+Builder+package+rename+proposal
This PR in particular converts `experience-builder-storybook-addon` to `experiences-storybook-addon`
Create feature branch called experience-release based on the development branch.
Ignored the `CHANGELOG.md` and `package-lock.json` files as those should be auto regenerated
=> refactor: rename experience-builder-storybook-addon to experiences-storybook-addon [ALT-395]

packages/validators/package.json, packages/validators/rollup.config.mjs, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/utils/zodToContentfulError.ts, packages/validators/src/validators.ts, packages/validators/test/utils/zodToContentfulError.spec.ts, packages/validators/test/v2023_09_28/componentSettings.spec.ts, packages/validators/test/v2023_09_28/componentTree.spec.ts, packages/validators/test/v2023_09_28/dataSource.spec.ts, packages/validators/test/v2023_09_28/experienceValidator.spec.ts, packages/validators/test/v2023_09_28/unboundValues.spec.ts, packages/validators/test/v2023_09_28/usedComponents.spec.ts, packages/validators/test/validator.spec.ts
Create mapping between zod errors and contentful errors. Also updated the test to check for the new format. For the mapping I am following closely what we're doing for Ajv error mapping [here](https://github.com/contentful/content-stack/blob/master/packages/errors/lib/ajv-to-contentful-error/index.js).
Now the validator function returns a list of errors in the format expected in our management API.
See also https://github.com/contentful/content_api/pull/9359 that integrates this validator into CMA.
In addition this PR includes a couple smaller changes:
* Compile the source code to commonJS format as content_api doesn't work with ESM.
* Don't rely on the caller to provide the schema version, but read it from the experience itself.
* Add `strict` option in a some of the schema to avoid …
=> feat: Convert zod to contentful errors [SPA-1701]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/test/v2023_09_28/componentTree.spec.ts
Property keys for imported components have a limit of 32 characters (to be implemented) while property keys for patterns have a limit of 54 characters (<32-char-variable-name>_<21-char-nanoid-id>). Because we cannot distinguish between the two in the componentTree, we will use the larger limit for both.
Note: we should reconsider how we create the property keys for patterns to align with imported components, this is a quick fix to unblock the validations work.
=> fix: increase property key length []

packages/components/src/components/Button/index.ts, packages/core/src/definitions/styles.ts, packages/storybook-addon/src/components/StyleSectionComponents/BackgroundImage/BackgroundImageInput.tsx, packages/storybook-addon/src/utils/variables.ts, packages/validators/test/__fixtures__/v2023_09_28/experiencePattern.ts
Ensure we have the display name to be Background image, Background color, Image scaling, and Image alignment
=> Update display names to Background image and Background color [ALT-460]

packages/visual-editor/src/components/Dropzone/useComponentProps.ts
In #430 I added a height transformation that is not correct. It seems that I manually set `height` to `100%` on both container which led to an overflowing content. However, that is a problem of the setting and not the pattern rendering logic. I saw that it is necessary that we render the actual height of each top-level container
=> revert: dont overwrite assembly block height manually [SPA-1869]

packages/visual-editor/src/components/Draggable/styles.module.css
Reproduction steps:
- create columns, switch the right column to fill 3 out of 12 grid columns.
- Put two elements inside the right column and align them horizontally
- Give the first of the two elements `100px` margin on the left and right side
This will "push" the second element outside the column and thus overflow the overall editor canvas.
When trying to scroll horizontally anywhere in the canvas, the user would first scroll some (wrong) wrapper in the DOM tree and then, on the second try, scroll the whole editor canvas as expected.
I described the bug and the solution in this Loom recording:
https://www.loom.com/share/e20358b7423f4846816ba6c1e406082a?sid=8a9e1e95-8725-4b92-805b-10f88da9a77b
You can also read the AI-generated summary:
> In this Loom, I discovered a specific bug …
=> fix: hide overflowing content []

.github/workflows/publish.yaml
To understand which prerelease belongs to which commit, we add the short hash to the version.
- The hash is after the datetime so we don't break any kind of ordering
- Skipping seconds as this information is not needed
- Using the 7-digit version like GitHub does by manually cutting after 7 letters.
Btw, there is `git rev-parse --short HEAD` but it creates a 10 digit hash. I think it's save enough (and so does GH apparently)
You can run locally this to see it in action:
```
echo "dev-$(date +%Y%m%dT%H%M)-$(git rev-parse HEAD  | cut -c1-7)"
```
=> chore: add github-like very short SHA to prerelease tag []

packages/visual-editor/src/components/Dropzone/Dropzone.tsx, packages/visual-editor/src/components/Dropzone/DropzoneClone.tsx, packages/visual-editor/src/components/Dropzone/EditorBlockClone.tsx, packages/visual-editor/src/hooks/useCanvasInteractions.ts, packages/visual-editor/src/store/tree.ts, packages/visual-editor/src/utils/getItem.ts, packages/visual-editor/src/utils/treeHelpers.ts
By implementing the cloning API offered from the hello-pangea/dnd [re-parenting docs](https://github.com/hello-pangea/dnd/blob/main/docs/guides/reparenting.md), we can prevent unwanted css transforms from reaching the draggable component by reparenting the draggable to the body of the document.
I ended up implementing a reparentChildNode fn in our smart tree update logic. With this enabled, causing a reparent event will instantly commit the changes to the tree instead of waiting for a postMessage from the user_interface with the updated tree. This removes component flickering when reparenting where the component was in it's old location until the update was received.
https://github.com/contentful/experience-builder/assets/23040747/40c674b7-b837-4dd8-b3a0-9ad67c285867
(The flickering …
=> fix(canvas-interactions): prevent draggables from flying off mouse cursor

.gitignore, .npmrc
Git ignores a previously committed .npmrc file, which had a registry reference to install @contentful namespace packages from github. This would cause an issue for users outside of CTFL that don't have access to CTFL github packages and could accidentally install packages from github packages that were meant to be installed from npm.
=> chore: add .npmrc file to gitignore

package-lock.json, packages/components/src/components/Button/index.ts, packages/components/src/components/Heading/index.ts, packages/components/src/components/Image/index.ts, packages/components/src/components/RichText/index.ts, packages/components/src/components/Text/index.ts, packages/core/src/definitions/components.ts, packages/core/src/types.ts
Update component defn to allow us and external users to define their own tooltips by adding 
```
tooltip?: {
imageUrl?: string;
description: string;
};
```
to the component defn.
Also adds tooltip defns for the following Basic components - heading, text, richtext, button, and image
=> feat: adds tooltip defn for heading, text, richtext, button, and image [ALT-462

packages/visual-editor/src/components/Draggable/styles.module.css, packages/visual-editor/src/components/Dropzone/Dropzone.tsx, packages/visual-editor/src/global.css
Assemblies (Patterns) should disable any Dropzones that are nested within itself since they are read-only.
Ticket: https://contentful.atlassian.net/browse/ALT-552
Disable Dropzones that are of the assembly node type. Also add a better comment to outline the "Rules of Dropzones"
=> fix(canvas-interactions): disable dropzones that are assemblies [ALT-552]

packages/components/src/components/Button/index.ts, packages/components/src/components/Heading/index.ts, packages/components/src/components/Image/index.ts, packages/components/src/components/RichText/index.ts, packages/components/src/components/Text/index.ts, packages/core/src/definitions/components.ts
Replace the term Elements with Components
Clean up the consistency between tooltip descriptions
=> fix: update component tooltips to use component term instead of elements [ALT-544]

packages/core/src/definitions/components.ts, packages/core/src/definitions/styles.ts
Adding the `cfImageSizes` variable to structure component definitions.
This variable is used for the Target Image Width input in the design sidebar when adding a Background Image to structure components.
=> fix: add cfImageSizes variable to structure components [ALT-514]

packages/core/src/constants.ts, packages/core/src/definitions/styles.ts, packages/core/src/types.ts, packages/core/src/utils/styleUtils/stylesUtils.ts
I decided to remove the `SUPPORTED_IMAGE_OBJECT_FIT` constant and use an object for the display names and values of each image object fit option in the UI:
* https://github.com/contentful/user_interface/blob/185408186abbfca07ac4dcb1326ed9faab035fb9/src/javascripts/features/experience-builder/components/StyleSectionComponents/ImageOptions/ImageFitSection.tsx#L14-L18
This makes the implementation a little more consistent with other style props such as Image Alignment options which follow this implementation:
* https://github.com/contentful/user_interface/blob/185408186abbfca07ac4dcb1326ed9faab035fb9/src/javascripts/features/experience-builder/components/StyleSectionComponents/ImageOptions/ImageAlignmentInput.tsx#L26-L36
=> fix: changes for Image Object Fit options [ALT-511]

packages/visual-editor/src/hooks/useEditorSubscriber.ts
The CanvasResized event would communicate the selected node ID and request for updated coordinates which was not being handled before and would cause issues with selected components and breakpoint changes.
Ticket: https://contentful.atlassian.net/browse/ALT-508
=> fix(visual-editor): component re-select on breakpoint change [ALT-508]

packages/visual-editor/src/components/EmptyContainer/EmptyContainer.tsx
Empty canvas now says `Add components to begin` rather than `elements`
=> fix: empty state canvas now says add components to begin

packages/core/src/definitions/styles.ts, packages/visual-editor/src/components/Draggable/styles.module.css, packages/visual-editor/src/components/Dropzone/styles.module.css
Ticket: https://contentful.atlassian.net/browse/ALT-323
Changes visual editor hover outlines to apply on `:before` psuedo-elements so that the outlines will always render on top.
* This makes it so the hover outlines will show on structure components that have a background image or background color.
This video compares hover outlines in Test App Prod  vs locally to show that the hover outlines works on the yellow background image section and green background color section (in the second half of the video):
https://github.com/contentful/experience-builder/assets/8539634/3ad38711-fa7e-421e-aa68-cbf829665b97
Changes the default border style to 0px so that we won't have a 1px transparent border on structure components by default
* This was causing the small gap between buttons that are …
=> fix: hover outlines and default border style [ALT-323]

packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx, packages/visual-editor/src/hooks/useSelectedInstanceCoordinates.ts
Based on the fix, I'm not sure why an app-router NextJS app was the only type of site causing this bug but essentially, our `handleClickOutside` fn was not properly checking if a click was actually outside of the canvas or not.
This resulted in every click first selecting the component, the event bubbling up, and then the `handleClickOutside` fn causing the component to immediately deselect. We have `e.stopPropagation()` on children of the canvas but I guess NextJS app-router behaves differently with an onClick event listener? Not entirely sure, but this code does feel more safeguarded for outside canvas clicks compared to before.
Also reduced the timeout for component select since our drop animation is removed.
=> fix(canvas-interactions): selecting a component in nextjs app-router [ALT-629]

packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx
https://github.com/contentful/experience-builder/pull/481 caused a small regression where selecting a component, deselecting it, and then reselecting the component would end up in a broken select state.
This small change ensures we properly clear the selected component so that reselecting works properly
=> fix(canvas-interactions): properly clear deselected component on canvas []

packages/experience-builder-sdk/src/index.ts
SDK currently exports some attributes that are only meant to be used either internally or in the interface with the Web app. There is no need to export those from the SDK so I am removing them here.
=> fix: remove unecessary exports from experience-builder-sdk

packages/visual-editor/src/components/Draggable/Placeholder.tsx, packages/visual-editor/src/components/Draggable/styles.module.css, packages/visual-editor/src/components/Dropzone/styles.module.css, packages/visual-editor/src/components/VisualEditorRoot.tsx
Placeholders were sometimes shown in the wrong location because they were not accounting for padding offsets or the flex alignment of the parent component. This PR adds logic to account for various alignments and padding values to more precisely render dropzone placeholders.
- Not being able to enable nested dropzones because of new overlays
- Adjust usage of `pointer-events: none` for proper drag and non-drag state behavior
https://github.com/contentful/experience-builder/assets/23040747/471a5a28-b5b5-443f-aa2e-c95d8f4c2d36
=> fix(canvas-interactions): proper placeholders based on padding and flex direction [ALT-505]

packages/visual-editor/src/components/Dropzone/EditorBlock.tsx, packages/visual-editor/src/types/constants.ts
The columns component does not allow dragging components in-between columns to add new columns. This is only handled via the column presets option in the design tab.
Because of this, we should not render hitboxes for the SingleColumn since they serve no purpose and only cause issues when many columns are added to the columns component. These hitboxes would overlap each other and end up making it seem like a user could not drop a component inside a column because that dropzone would never get enabled.
=> fix(canvas-interactions): do not render hitboxes for single column [ALT-571]

packages/visual-editor/src/components/VisualEditorRoot.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/src/store/entityStore.ts
Remove useEffect in VisualEditorRoot as it was resetting entity store reactively. Which in some case ends up having empty canvas.
=> fix: locale switching does update content in canvas [SPA-1949]

packages/core/src/types.ts, packages/experience-builder-sdk/src/core/componentRegistry.test.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/hooks/useInitializeVisualEditor.ts, packages/validators/src/schemas/componentDefinition.ts, packages/validators/src/schemas/index.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/types.ts, packages/validators/src/validators.ts, packages/validators/test/__fixtures__/componentDefinition.ts, packages/validators/test/validator.spec.ts
* Extend validations to make sure component `definitionId` doesn't not contain invalid characters and has max limit of 32
* Validate components during component registration - **only on editor mode**
* Define a simple validator function for component registrations
* [In Editor Mode] Run the validation when a new component is registered
* throw an error if the validation fails
* Validation doesn't ran on preview/delivery mode to avoid introduction exception in the customer's website.
=> fix: extend validators to validate component registration on editor mode [SPA-1899]

packages/core/src/utils/transformers/media/getOptimizedBackgroundImageAsset.spec.ts, packages/core/src/utils/transformers/media/getOptimizedImageAsset.spec.ts, packages/core/src/utils/transformers/media/getOptimizedImageUrl.spec.ts, packages/core/src/utils/transformers/media/getOptimizedImageUrl.ts
Changes the `getOptimizedImageUrl` method to specify https instead of using protocol agnostic urls that come back from the image API.
This prevents the "Mixed Content" error when running the hosted app locally on http. 
I tested images and background images with the test-app running locally, and with the hosted test-app on vercel and I'm not seeing any unexpected side effects.
=> fix: convert protocol agnostic image asset url to https [ALT-639]

packages/validators/rollup.config.mjs
Build a single index.d.ts file instead of preserving modules.
Update rollup config to generate a single types file to avoid the error described below:
With preserving modules before, each file would generate its own `.d.ts` file in the `/dist` folder which led to an weird error where the `componentDefinitions.d.ts` would not declare the `ComponentDefinitionSchema` variable:
causing an error in the package:
The error was only observed once we tried to install the package in content_api.
With the new approach ComponentDefinitionSchema is declared in index.d.ts:
=> fix: build a single index.d.ts file instead of preserving modules

packages/core/src/definitions/styles.ts, packages/core/src/types.ts
Defaulting the image component to object fit none lead to unexpected behavior so we are opting to make objectFit undefined as an initial value so that it has no styling effect by default.
=> fix(components): change image object fit to default to undefined instead of none []

packages/core/src/fetchers/fetchAllEntities.spec.ts, packages/core/src/fetchers/fetchAllEntities.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/fetchReferencedEntities.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
Previously we only fetched 100 referenced entities. So for experiences with more than 100 entities bound, we only render 100 entities.
This PR fetches all bound entities in chunks of 100. 
If we encounter a response too big error during fetch, we reduce the limit and try fetching again.
https://github.com/contentful/experience-builder/assets/30434146/0b86e386-76ca-4e31-a07c-68ea0e628dc2
=> fix: fetch all referenced entities 

packages/experience-builder-sdk/src/hooks/useStyleTag.spec.ts, packages/experience-builder-sdk/src/hooks/useStyleTag.ts
Styling in Experiences is currently a process that happens solely client-side. The hook used to inject styles, `useStyleTag`, uses a combination of state/effect to create the correct style rules and append them to the document head. Since React runs effects after DOM is updated, this approach has meant that there is always at least one render pass where the output is unstyled.
Given that none of the work that `useStyleTag` does is asynchronous, we can refactor it process such that:
- Styles are memoised, rather than stateful; this better reflects the fact that they are a product of props rather than something the hook itself can change over time.
- Styles are appended the DOM using a layout effect. Given that these run before paint, this means that styles are immediately available for …
=> refactor(experience-builder-sdk): synchronous style calculation

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx
This change allows the `children` variable to be used for content, as long as the component definition does not have also have `children: true` enabled (which registers a drop-zone container for nesting children components)
Ticket: https://contentful.atlassian.net/browse/ALT-636
Now the `children` variable can render the bound content in live mode:
=> fix(experience-builder-sdk): children variable for text content [ALT-636]

packages/core/src/types.ts
add borderRadius type for design tokens
=> feat: add borderRadius type for design tokens

packages/core/src/constants.ts, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/index.ts, packages/test-app/src/App.tsx, packages/visual-editor/src/components/Dropzone/useComponent.ts
BREAKING CHANGE:
Any existing experiences using the basic components will need to be updated. To do so, import and run the `maintainBasicComponentIdsWithoutPrefix` method and run it early on in your application (before the first `ExperienceRoot` is rendered) like so:
```tsx
import { maintainBasicComponentIdsWithoutPrefix } from '@contentful/experiences-sdk-react';
maintainBasicComponentIdsWithoutPrefix();
```
This will register a set of the basic components with the older ids and allow your experiences to continue to work. To migrate to the new components, replace any of the components marked with "[OLD]" in the editor with their newer counterparts (without the '[OLD]').
The `maintainBasicComponentIdsWithoutPrefix` is meant to help older experiences built on a early alpha release to …
=> feat(experiences-sdk-react)!: update basic component IDs with contentful prefix

packages/core/src/definitions/styles.ts, packages/core/src/types.ts, packages/core/src/utils/transformers/media/getOptimizedBackgroundImageAsset.spec.ts, packages/core/src/utils/transformers/media/getOptimizedBackgroundImageAsset.ts, packages/core/src/utils/transformers/media/getOptimizedImageAsset.spec.ts, packages/core/src/utils/transformers/media/getOptimizedImageAsset.ts, packages/core/src/utils/transformers/media/mediaUtils.ts, packages/core/src/utils/transformers/media/transformMedia.ts
After the refactoring to reduce the number of variables, image quality was being passed down to the Experience with a percentage symbol, which before it was just a string with the number in it. Updated the code to expect the percentage and remove it before converting it to a number.
=> fix(core): expect image quality to be a string with a percentage [ALT-643]

packages/experience-builder-sdk/src/core/componentRegistry.test.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts
I noticed that if I called `defineComponents` function more than once, I would get the following error
Notice that the part of visible payload looks like a react component function.
Turns out that we were not properly filtering the component registry and instead of component definitions, were attempting to send the entire registry object
Steps to reproduce:
* call `defineComponents` function twice
=> fix: do not attempt to send components via postMessage

packages/visual-editor/src/components/Dropzone/useComponent.ts
Attempting to prevent the SDK error `Cannot read properties of undefined (reading 'definition')` in the useComponent hook.
I don't know of a way to reproduce the issue that triggers this error. However, I think the problem stems from type casting the result of this call to `createAssemblyRegistration` which can return `undefined` but would not be caught by the branch that throws an error.
Ticket: https://contentful.atlassian.net/browse/ALT-654
=> fix(visual-editor): throw error when component registration not found in useComponent hook [ALT-515]

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/cleanup.yaml, .github/workflows/publish.yaml, README.md, lerna.json, packages/components/package.json, packages/core/package.json, packages/create-experience-builder/package.json, packages/storybook-addon/package.json, packages/validators/package.json
This PR prepares the monorepo for the upcoming stable release.
- The versioning of the project was changed to used fixed versioning, so each package will published using the same version number. This will help cut down confusion on which package is being used for debugging scenarios. The downside is that each package will get published wether there was a change in them or not. This shouldn't be too big of an issue, however, as the only package meant to be installed by users is `@contentful/experiences-sdk-react`.
- The fixed versioning will also give us a changelog that will live at the root of the repo which will contain changes to all of the packages.
- The `next` branch will now do a 'beta' release instead of an 'alpha' release.
- The `main` branch will do a stable release with the …
=> Prep repo for stable GA release - [ALT-468]

packages/core/src/fetchers/fetchAllEntities.spec.ts, packages/core/src/fetchers/fetchAllEntities.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/fetchReferencedEntities.ts, packages/core/src/test/__fixtures__/entities.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
Fetch all references with includes
https://github.com/contentful/experience-builder/assets/30434146/1ecc9c3d-d1bc-42b4-84e7-b42ec9f03922
With Deep Binding
https://github.com/contentful/experience-builder/assets/30434146/6995a186-42a1-4f1e-8f7c-1eb8ec82238e
=> fix: fetch all references with includes

packages/components/src/components/Image/index.ts, packages/core/src/definitions/styles.ts, packages/storybook-addon/src/utils/variables.ts
Making border radius an optional style and fixing the issue where images don't take on the border radius value
=> fix: add border radius to image component and make border radius an optional style

.gitignore, packages/components/README.md, packages/components/cypress/support/component.ts, packages/components/package.json, packages/components/rollup.config.mjs, packages/components/src/components/Image/Image.css, packages/components/src/styles.ts, packages/create-experience-builder/templates/react-vite-ts/src/App.tsx, packages/test-app/src/Page.tsx
Removes the generated styles.css from the component project. This file was no longer used. If you were importing it, remove the import.
=> fix(components)!: removing styles.css file from components

packages/components/src/components/RichText/RichText.css, packages/components/src/components/RichText/RichText.cy.tsx, packages/components/src/components/RichText/RichText.tsx
Ticket: https://contentful.atlassian.net/browse/ALT-585
Adds a wrapping `<span>` around the document in the RichText component.
* Previously the component `props` were being spread to each paragraph node, which was causing an issue with rendering.
I also added a couple of styles to remove the margin-top from the first element, and remove the margin-bottom from the last element in the RichText editor.
* This way the top and bottom margin's are not forced, and the user can control the exact amount of margins they want using the design sidebar.
=> fix(components): rich text formatting [ALT-585]

packages/visual-editor/src/communication/sendSelectedComponentCoordinates.ts
This fixes the selected component outline when changing images.
Ticket: https://contentful.atlassian.net/browse/ALT-646
https://github.com/contentful/experience-builder/assets/8539634/9ae57ece-2700-42af-99e0-c2dc4146bd5b
=> fix(visual-editor): select component when image loads [ALT-646]

packages/core/src/utils/components.ts, packages/visual-editor/src/components/Dropzone/Dropzone.tsx, packages/visual-editor/src/components/Dropzone/EditorBlock.tsx, packages/visual-editor/src/components/Dropzone/Hitboxes.tsx, packages/visual-editor/src/components/Dropzone/styles.module.css, packages/visual-editor/src/utils/getHitboxStyles.ts
Ticket: https://contentful.atlassian.net/browse/ALT-561
Changes to Dropzones and Hitboxes to allow root-level structure components to be reparented other structure components on the canvas.
https://github.com/contentful/experience-builder/assets/8539634/57728ee6-3cc7-4198-96a2-98028284eef8
Video demonstrating that dropzones are activating as expected for different scenarios:
* Adding a new structure component 
* Adding a new basic component
* Moving a basic component
* Moving a structure component (the bug being fixed)
=> fix: allow root-level structure components to be reparented into siblings [ALT-561]

packages/core/src/constants.ts, packages/core/src/utils/styleUtils/styleTransformers.ts, packages/core/src/utils/styleUtils/stylesUtils.ts
* Fixes the issue with `transformWidthStyle()` method that was applying the style `width: 100%` instead of `width: calc(100% - marginLeft - marginRight)` in SSR mode
Ticket: https://contentful.atlassian.net/browse/ALT-749 (Point 1)
=> fix(core): adjust transformWidthSizing to support SSR [ALT-749]

packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx
This change allows the first and last root dropzones to activate on the canvas when moving components that are already on the canvas.
Previously the first and last root dropzones would only activate when dragging in new components from the sidebar due to the condition checking for `draggingNewComponent`
https://github.com/contentful/experience-builder/assets/8539634/5ad47f5d-e64b-40a7-983d-1d735cb64408
=> fix(visual-editor): root dropzones [ALT-746]

packages/experience-builder-sdk/src/components/ErrorBoundary.tsx, packages/visual-editor/src/components/Dropzone/ImportedComponentErrorBoundary.tsx, packages/visual-editor/src/components/Dropzone/useComponent.ts
Wrap custom component in their own error boundary to make it possible to separate errors coming from imported components vs our own SDK code.
=> fix: don't track errors thrown from imported components [SPA-1995]

CHANGELOG.md, lerna.json, package-lock.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/experience-builder-sdk/CHANGELOG.md, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/components/ErrorBoundary.tsx, packages/validators/CHANGELOG.md, packages/validators/package.json, packages/visual-editor/CHANGELOG.md, packages/visual-editor/package.json, packages/visual-editor/src/components/Dropzone/ImportedComponentErrorBoundary.tsx, packages/visual-editor/src/components/Dropzone/useComponent.ts, packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx
* [fix: don't track errors thrown from imported components](https://github.com/contentful/experience-builder/commit/070360f1910c73ba0c81e2d24b9c64fb812cdf32)
* [fix(visual-editor): allow first and last root dropzones to activate when moving components](https://github.com/contentful/experience-builder/commit/090181e7f923a7146b1dc4af181c2f3c4fb3e02e)
=> Release@main

packages/core/src/utils/styleUtils/stylesUtils.ts, packages/visual-editor/src/components/Dropzone/Hitboxes.tsx, packages/visual-editor/src/components/Dropzone/useComponentProps.ts, packages/visual-editor/src/components/RootRenderer/DNDProvider.tsx, packages/visual-editor/src/components/RootRenderer/TestDNDContainer.tsx, packages/visual-editor/src/hooks/useDraggablePosition.ts, packages/visual-editor/src/utils/getHitboxStyles.ts
This change fixes Issue 2 in [ALT-746](https://contentful.atlassian.net/browse/ALT-746) 🐛
I found that the issue was a result of setting the drag state via calling `setDraggingOnCanvas(true)` in the DNDProvider's `onBeforeCapture` - which is before the dimensions have been captured from the DOM based on the [docs](https://github.com/hello-pangea/dnd/blob/main/docs/guides/responders.md#life-cycle-%EF%B8%8F)
To fix the main issue, I moved this call to set the drag state in DNDProvider's `onBeforeDragStart` responder instead so that it won't happen until the DND capture phase has completed.
After that change, the dropzone where the root-level component was picked up from starts activating as expected when moving the dragged component around and then trying to move it back to its original …
=> fix: activate original dropzone when moving root-level components [ALT-746]

packages/visual-editor/src/components/Dropzone/useComponentProps.ts
Fixes an issue in the `addExtraDropzonePadding` method that causes structure components with non-pixel padding values to be overwritten with `4px` padding (via `DRAG_PADDING` const) when dragging components.
For example, this section has `5%` left/right padding, and when starting to drag the padding is changed to `4px` (to show the bug that was happening before the change)
https://github.com/contentful/experience-builder/assets/8539634/902c873d-0a55-4123-897d-68afebcf1951
With this change, only the sides with 0 padding or a pixel value less than 4px will be adjusted to 4px padding:
https://github.com/contentful/experience-builder/assets/8539634/6d3784b2-cf2d-4175-ad4c-c4b407e696ac
The purpose of this `addExtraDropzonePadding` method is to add a little padding when dragging, so that …
=> fix(visual-editor): extra dropzone padding when dragging [ALT-746]

packages/components/src/components/Image/Image.tsx, packages/core/src/types.ts, packages/core/src/utils/transformers/media/getOptimizedImageAsset.spec.ts, packages/core/src/utils/transformers/media/getOptimizedImageAsset.ts, packages/core/src/utils/transformers/media/transformMedia.ts
Customers would like to add lazy loading to their images
Extends the ImageOptimization options to include a loading flag that can be set to 'lazy', 'eager', or undefined, which is configured via the UI. This option will set its value to the `loading` attribute on the option.
=> feat(components): add loading attribute to image component

packages/core/src/definitions/styles.ts, packages/core/src/utils/styleUtils/styleTransformers.ts
With the updates to the new input styles on Experiences canvas on the ui side, these fill values are no longer valid since the ui doesn't convert fill into a relative 100% option and is instead better to use the actual valid css value of 100%.
Note that in `styleTransformers.ts` this block of code was kept for backwards compatibility
```
// Keep this for backwards compatilibity - deleting this would be a breaking change
// because existing components on a users experience will have the width value as fill 
// rather than 100%
export const transformFill = (value?: string) => (value === 'fill' ? '100%' : value);
```
=> [ALT-692] feat: update definitions of fill to use 100% for components

package-lock.json, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/visual-editor/package.json, packages/visual-editor/src/components/Dropzone/useComponentProps.spec.ts, packages/visual-editor/src/components/Dropzone/useComponentProps.ts, packages/visual-editor/vitest.config.ts
When rendering a pattern in the editor, as a standalone pattern, outside of an experience, we need to still render the default (placeholder) values into the canvas to assist designers when adjusting the pattern.
This PR makes sure that when we encounter a property with type `ComponentValue` (only available for patterns) we render the default value of the component.
=> fix: render default content values for patterns [SPA-2048]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/test/__fixtures__/v2023_09_28/experience.ts, packages/validators/test/v2023_09_28/componentTree.spec.ts
Adds an optional `displayName` field to the `ComponentTreeNode` type.
* We can use this field to allow custom names to be set for each component instance on the canvas or layer.
For a cleaner diff, use the 'Hide whitespace' option in the diff settings on the File Changes tab.
=> feat(validators): add optional displayName to ComponentTreeNode [ALT-780]

packages/core/src/utils/styleUtils/styleTransformers.ts
fix bug where width in editor does not change if user does not have margin as a prop
[https://contentful.atlassian.net/jira/software/c/projects/ALT/boards/1552?selectedIssue=ALT-792]
- removed check in width transformation that returns undefined if no margin prop
=> fix: remove check if no margin

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/test/v2023_09_28/componentTree.spec.ts
Added an optional `slotId` field to the `ComponentTreeNode` schema to support multiple dropzone slot locations per component.
This field allows nested child nodes to be identified and filtered by their slot locations. By having this data persist in the entries API, we can accurately reconstruct the component tree from an experience entry with data-level support for multiple dropzone slots per component.
Additional changes are needed to the User Interface and SDK to implement full support for multiple dropzone locations per component (this change is only for the API data layer).
=> feat(validators): add optional slotId to component tree node

packages/core/src/utils/breakpoints.ts
maxWidth currently does not work if you use design tokens for the value
Add maxWidth to the list of styles that use design tokens so that the code knows to resolve the design token value
https://www.loom.com/share/f86d1c370ab04e9d94befe3410fac2ca?sid=070c270d-72ee-4282-958c-10c7b729fd22
=> fix: add maxWidth to list with design tokens

README.md
Add github documentation at the root level repo
=> [ALT-817-root] feat: update github readme at the root level for more direct links and more detailed explanations

package-lock.json, packages/visual-editor/src/components/Draggable/DraggableChildComponent.tsx, packages/visual-editor/src/components/Draggable/DraggableComponent.tsx, packages/visual-editor/src/components/Dropzone/EditorBlock.tsx
should show custom display name of component on hover overlay
https://contentful.atlassian.net/browse/ALT-688
=> fix: show custom display name on hover of component

packages/core/src/constants.ts, packages/core/src/registries/breakpointsRegistry.spec.ts, packages/core/src/registries/breakpointsRegistry.ts, packages/core/src/registries/index.ts, packages/experience-builder-sdk/src/core/componentRegistry.test.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/hooks/useInitializeVisualEditor.ts, packages/experience-builder-sdk/src/index.ts, packages/test-app/src/eb-config.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators.ts, packages/validators/test/v2023_09_28/componentTree.spec.ts, packages/validators/test/v2023_09_28/experienceValidator.spec.ts
To enable users to define their custom breakpoints, this PR exposes the `defineBreakpoints` function.
Wrong ❌
`
defineBreakpoints([
{
id: 'test-desktop',
query: '*bnsmqw',
displayName: 'All Sizes',
previewSize: '100%',
},
{
id: 'test -tablet',
query: '<982px',
displayName: 'Test Tablet',
previewSize: '820px',
},
{
id: 'test-mobile',
query: '<1000px',
displayName: 'Second Test Tablet',
previewSize: '820px',
},
{
id: 'test-mobile',
query: '>400px',
displayName: 'test-Mobile',
previewSize: '390px',
},
{
id: 'test-mobile',
query: '>360px and <1000px',
displayName: 'test-Mobile',
previewSize: '390px',
},
])
`
https://github.com/contentful/experience-builder/assets/30434146/750d17d8-d640-47d2-ab92-d293c95fd830
Correct ✅
`defineBreakpoints([
{
id: 'test-desktop',
query: '*',
displayName: 'All …
=> feat: expose function to define custom breakpoints [SPA-2076]

packages/core/src/registries/breakpointsRegistry.ts
Prevent the editor from throwing an error when breakpoints are not defined
We provide a default fallback breakpoint in the UI, so it doesn't make sense to disrupt the editor when the user doesn't define breakpoints.
=> fix: remove error when breakpoints are not defined [SPA-2078]

packages/core/src/constants.ts, packages/experience-builder-sdk/src/core/sdkFeatures.ts, packages/experience-builder-sdk/src/hooks/useDetectEditorMode.tsx
Create sdk feature detection object in core. Then send it as a post message to the ui
=> [ALT-830] feat: add sdk feature detection object in core

.github/workflows/main.yml, .github/workflows/publish.yaml, README.md
* Contributors from time to time want to publish specific builds to the public repo so they can be installed elsewhere (eg in user interface PRs where dependent changes are made)
* Use existing workflow dispatch on main branch and add a toggle that allows a prerelease to be built for the selected branch
* Artifact uses same naming convention and lerna option as existing prerelease for `development` branch, except the preid is `prerelease` instead of `dev`. The dist-tag assigned is `prerelease`
=> Allow package versions to be manually published as pre-releases for a selected branch

.github/workflows/main.yml
When a PR is merged a "push" event occurs and the value of the recently added `publish-prerelease` input is not false or null but rather an empty string. This doesn't match the required type here https://github.com/contentful/experience-builder/blob/development/.github/workflows/publish.yaml#L6-L10 .
To get this working we'll need to cast the input to a boolean.
Example failed workflow: https://github.com/contentful/experience-builder/actions/runs/9323345098
* Coerce the value to a boolean using a double bang (`!!`). According to the GIthub Action docs (https://docs.github.com/en/actions/learn-github-actions/expressions) "in conditionals, falsy values (false, 0, -0, "", '', null) are coerced to false and truthy (true and other non-falsy values) are coerced to true."
=> chore: handle default string input gracefully

packages/core/src/registries/designTokenRegistry.ts, packages/core/src/types.ts, packages/experience-builder-sdk/src/core/componentRegistry.ts
To make composite values optional when defining design tokens like border where it consists of a width, color, and style property.
When creating the in memory design token structure, make sure the values are all set during construction. Only composite design tokens like border and eventually text need to be checked because simple key-value DTs are enforced by typescript.
Use `1px` as a fallback default for width
Use `black` as a fallback default for color
Use `solid` as a fallback default for style
```
Used this for my DTs where I had a width, color, and style missing
// register design tokens
defineDesignTokens({
border: {
Azure: { style: 'solid', color: 'azure' },
Card: { width: '1px', style: 'solid' },
Carousel: {},
Hero: { width: '2px', color: '#ffaabb' },
},
});
```
which then …
=> feat: allow for optional composite design token values in experiences

packages/core/src/utils/styleUtils/styleTransformers.spec.ts
`transformWidthSizing` was removed in a [different PR](https://github.com/contentful/experience-builder/pull/643) so the tests for it are no longer needed.
=> test: remove tests for already removed function []

packages/core/src/definitions/styles.ts, packages/experience-builder-sdk/src/utils/ssrStyles.spec.ts
Only have default background color for components that need to have them which at this point is the `Button` and `Divider` component
https://www.loom.com/share/d44ced7d7abf4350898ec459c4448e86?sid=c7105e44-928c-4616-99f3-68f27579c313
=> [ALT-911] fix: only have default background color for components that need to have them

package-lock.json, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/rollup.config.mjs, packages/experience-builder-sdk/src/ExperienceRoot.tsx, packages/experience-builder-sdk/src/hooks/useDetectEditorMode.tsx, packages/experience-builder-sdk/src/hooks/useFetchByBase.ts
Allows importing code direclty from `@contentful/experiences-sdk-react` from NextJS server components.
Right now we have a workaround to import certain pieces from `@contentful/experiences-core` as importing them in a NextJS server component will throw an error. This fix allows those components to now be successfully imported from the main sdk.
Ticket: https://contentful.atlassian.net/browse/ALT-1010
I added `use client` directives to components that use anything from React that requires client side (useState, useLayoutEffect, etc..). This instructs Next that these are client components, and it will import them as such. This change should have no effect on other frameworks as the 'use client' directive should simply be ignored by them.
To get this to work, I had to change the rollup build …
=> fix: allow experiences-sdk-react components/hooks to be imported in NextJS server components

packages/core/src/fetchers/gatherAutoFetchedReferentsFromIncludes.spec.ts, packages/core/src/fetchers/gatherAutoFetchedReferentsFromIncludes.ts
When an entry or asset was deleted which is used in a deep-bound value, the app would just crash in preview mode. Similarly to other places in the code, we want here also a less disrupting experience but just ignore broken bindings.
Similar to other cases covered in `gatherAutoFetchedReferentsFromIncludes`, we will create a debug message instead of throwing a crashing error.
=> fix: resilient resolve logic of deep bindings [SPA-2110]

packages/test-apps/nextjs/src/eb-config.ts, packages/test-apps/react-vite/src/eb-config.ts
Currently, the test app defines no breakpoint icons. This makes the editor currently render the fallback icon.
Note that this change requires updating the breakpoints via the editor.
Before:
After:
=> fix(test-app): define display icon for test-app breakpoints []

packages/visual-editor/src/hooks/useEditorSubscriber.spec.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/test/__fixtures__/assembly.ts, packages/visual-editor/test/__fixtures__/assemblyDefinition.ts, packages/visual-editor/test/__fixtures__/tree.ts, packages/visual-editor/test/pact/PactConsumer.ts, packages/visual-editor/test/pact/index.ts, packages/visual-editor/test/pact/interactions.ts
Implement consumer contract tests for ExperiencesSDKConsumer.
* Each interaction includes an example payload and a payload matcher as well as a unique id. 
* Each interaction is run through the `createPostMessageReceiver` function which renders the `useEditorSubscriber` hook and triggers a message with the specified payload.
* Each interaction created a pact in the `pacts/ExperiencesSDKConsumer-UserInterfaceProvider.json` file. (This file is ignored by git, but running the tests locally will generate it and can be inspected)
* For each interaction we run a set of assertions based on what is expected to happen when the specific message is received.
* Some trivial events with no payload have been ignored.
=> test: experiences SDK consumer pacts [SPA-2129]

packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx, packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/hooks/useSingleColumn.ts
Allow users to reorder single columns in a column component from the canvas. This is purposely only enabled when columnWrap is turned off as the complexity of reorder across rows and columns breaks dnd.
Ticket: https://contentful.atlassian.net/browse/ALT-802
https://github.com/user-attachments/assets/71a5c445-aca4-40d0-8473-198022974fd6
=> feat: implement column reorder [ALT-802]

packages/core/src/test/__fixtures__/experience.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/test/__fixtures__/assembly.ts, packages/visual-editor/src/hooks/useComponentProps.ts, packages/visual-editor/src/utils/assemblyUtils.spec.ts, packages/visual-editor/src/utils/assemblyUtils.ts, packages/visual-editor/test/__fixtures__/assembly.ts
With the new feature of exposing design properties for pattern instances, they can now be of type `ComponentValues` inside the tree of a pattern.
Similar to the previously implemented content variables, we're replacing those with the value of the componentValue when rendering the respective assembly child node.
=> feat: support rendering of component values for design properties [SPA-2145]

packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx, packages/visual-editor/src/components/DraggableBlock/styles.module.css, packages/visual-editor/src/hooks/useComponent.tsx
Whether you are in delivery or edit mode, a pattern always adds a wrapping div to the content. This is because a pattern can have multiple root children so it's required to be wrapped in an element to be handled by the SDK.
The problem is that this div has `display: contents` in delivery mode so to the end user it seems to not exist but we can't use `display: contents` in editor mode because we need to be able to drag that root pattern element around on the canvas. 
To solve this for most use-cases we've added width: 100% to the root pattern node in editor mode
Ticket: https://contentful.atlassian.net/browse/ALT-1036
https://github.com/user-attachments/assets/5773e83b-ca24-4bd1-9f16-b6f501f9790a
=> fix: full-width for pattern wrapper [ALT-1036]

packages/visual-editor/src/components/RootRenderer/DNDProvider.tsx
Fixes [ALT-1038]
Dragging a structural component and dropping it in its own position could have an issue where the SDK thinks it switching the parent of the component to itself, which would remove it from the tree. I put a check in that if the droppable id is the same as the draggable id, to nope out of the operation.
This uncovered what could be a potential race condition in the `isDropZoneEnabled` [check](https://github.com/contentful/experience-builder/blob/d48b81a4de4bbaf7deddf5928646db95335e1968/packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx#L95), in which the hovered element could briefly be set back to the component being dragged, which would result in the drop zone of the dragging component not be appropriately disabled.
[ALT-1038]: …
=> fix: fix issue where dragging a structure component could periodically make it go bye bye

packages/visual-editor/src/components/DraggableHelpers/Placeholder.tsx
When we refactored the SDK to no longer include a wrapping div, placeholder styles needed to be updated to reference sizing from the correct element. Instead of referencing the `.parentElement` it needed to reference the element itself since the wrapping div no longer applies.
Ticket: https://contentful.atlassian.net/browse/ALT-1011
=> fix: incorrect placeholder styling [ALT-1011]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/visual-editor/src/hooks/useComponentProps.ts
When binding an entry and deleting the entry afterward, I saw the default content value "Heading" in the editor but in preview the whole component was not rendered at all.
So far, we did not fall back to the default values in preview mode. After aligning with design & product, this is now streamlined with the editor mode.
=> fix(experience-builder-sdk): render defaultValue in preview when resolving doesnt work [SPA-2206]

packages/core/src/utils/styleUtils/ssrStyles.ts, packages/core/src/utils/styleUtils/ssrStylesPattern.spec.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts
With Editable patterns we now have different styles for each pattern instance, which needs to be considered when detaching styles for SSR.
Pattern instances can have different styles due to Editable patterns, we have to store styles depending on the pattern instance in an experience rather than the pattern node itself.
We generate a unique identifier for each child component of a pattern and associate this identifier with the corresponding node. The style classes are then stored in the pattern wrapper node, keyed by these unique identifiers.
This approach ensures that the styles for each pattern’s instance are maintained separately, preventing conflicts.
- Types needs to be adjusted as id doesn't exist currently in `ComponentTreeNode`
=> fix: ssr styles extraction for editable patterns [SPA-2157]

packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx, packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/components/DraggableBlock/styles.module.css
Fixes a bug with the custom components not accepting children to be dragged into the dropzone as expected.
The issue had two sides:
* First, the visual editor outlines were not rendering for `.Dropzone` elements
* Fix: I added the `.Dropzone` selector to match the `.DraggableComponent` styles and included a `:not(.isSlot)` to prevent double-outlines rendering on Slot dropzones.
* Second, in `<EditorBlock>` the `userIsDragging` boolean was associated with a conditional `.userIsDragging` style, but those styles were replaced [in this PR](https://github.com/contentful/experience-builder/pull/635/files#diff-28d89a9f8f144ff448bc930e3241ff66dace31da1199a21b789b00ba852ae457) with the `.isDragging` class
* Fix: I moved the `userIsDragging` boolean to be an OR condition on the conditional …
=> fix(visual-editor): styling for custom component children dropzone [ALT-1085]

package-lock.json, packages/components/src/components/Divider/ContentfulDivider.tsx, packages/test-apps/react-vite/src/studio-config.ts
Props weren't spread on the root component of the divider making it not selectable in editor mode
=> fix: divider not selectable in editor mode [ALT-1120]

packages/core/src/definitions/styles.ts
We're changing the default background color opacity to 0 to work better with the design sidebar accordion in the UI
Ticket: https://contentful.atlassian.net/browse/ALT-887
=> feat(core): set background color opacity to 0 by default [ALT-887]

packages/components/src/components/RichText/RichText.cy.tsx, packages/components/src/components/RichText/RichText.tsx
Adding design variables to a rich text component would not always display them properly.
The rich text component was wrapping the outputs of the call to `documentToReactComponents` in a span tag, which is an inline level element. The markup that `documentToReactComponents` creates contains block level elements, and wrapping block level elements in an inline element can break layout flow (which we saw in this bug).
The issue was fixed by replacing the `span` tag with a `div` tag as the wrapper.
=> fix: don't wrap rich text with an inline element

packages/validators/src/schemas/v2023_09_28/experience.ts
Using the union type `ComponentPropertyValue` is not strict enough and requires some additional typeguarding inside the customer application.
Export the type explicitly same as for `UnboundValue` & co.
=> feat: expose the HyperlinkValue type to consume it directly [SPA-227]

packages/core/src/registries/breakpointsRegistry.spec.ts, packages/test-apps/nextjs/src/studio-config.ts, packages/test-apps/react-vite/src/studio-config.ts
Fixes rendering for mobile breakpoint styles in the test apps.
The mobile breakpoint definition in the test apps was using the query `<360px` that was lower than the previewSize `390px`. Essentially telling the UI to render a 390px wide iframe preview and apply mobile styles when the viewport is below 360px.
I changed the mobile breakpoint query to `<576px` to match the [example custom breakpoints registration](https://www.contentful.com/developers/docs/experiences/register-custom-breakpoints/#example-custom-breakpoints-registration)
For experiences created with the previous breakpoint config, each dev/user will need to update their experiences using the "Update breakpoints" button that displays in the design sidebar when no component is selected:
And then "Update breakpoints" in the …
=> fix: test apps mobile breakpoint config [ALT-1167]

packages/core/src/definitions/styles.ts
Second half of fixed margin for the Container component. We needed to fix the default value to be `margin: 0 auto 0 auto`.
Ticket: https://contentful.atlassian.net/browse/ALT-1166
Linked PR: https://github.com/contentful/user_interface/pull/23002
=> fix: default value for container margin to be auto left/right [ALT-1166]

packages/visual-editor/src/components/DraggableHelpers/ImportedComponentErrorBoundary.tsx
The "imported component" error boundary seems to swallow any error in our rendering logic. When I turn [this warning](https://github.com/contentful/experience-builder/blob/b0213c0e261cf6c1219af99a238282f92f67438a/packages/visual-editor/src/hooks/useComponent.tsx#L58) again into an error, it gets swallowed. I assume that is because the boundary will wrap not only the component (whether custom or built-in) but also any logic inside its children and thus again the logic for the children inside `useComponent`. The top-level section component will already add the first boundary and thereby swallow any error regarding component registration, child rendering, etc.
Introduce a new error class that explicitly not gets swallows:
=> fix: dont swallow errors that are originated inside the SDK [SPA-2189]

packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/components/DraggableBlock/styles.module.css
Hovering over a pattern in the layers tab now looks like this 
It uses the display name of the pattern
https://www.loom.com/share/1a504adca3cb4431a9d1e1d0d5bfc44d?sid=ae67f77c-bf40-43b6-82d1-1fb7580085bb
=> [ALT-1061] fix: hovering pattern in layers tab now renders the display name on canvas in studio experiences

packages/core/src/utils/breakpoints.spec.ts, packages/core/src/utils/breakpoints.ts
Make sure that `getValueByBreakpoint` doesn't crash if current index doesn't match any breakpoints.
Fixes https://contentful.sentry.io/issues/5794748829/
`getValueByBreakpoint` should be more defensive against a `currentIndex` that doesn't match any breakpoints otherwise the above error will happen and will crash the app.
Normally `currentIndex` should correspond to a breakpoint but since we cannot ensure that the caller has verified this we should handle this case more gracefully. It seems that a customer has already ran into this issue but since I cannot reproduce it on my side it's hard to tell where in the workflow the current index gets a wrong value.
=> fix: type error when breakpoint is undefined

packages/core/src/definitions/styles.ts, packages/core/src/types.ts, packages/experience-builder-sdk/src/core/componentRegistry.test.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/core/sdkFeatures.ts, packages/test-apps/react-vite/src/studio-config.ts
Introduce a cfVisibility style prop variable to the default style definitions
- Add ` cfVisibility` to cf component default style definitions
- For custom components, add ` cfVisibility` default variable on component registration
=> feat: add style prop to toggle visibility in component registration [SPA-2371]

packages/components/src/components/RichText/index.ts
Enable the `cfTextColor` built in style option for the Rich Text built-in component
=> feat: enable text colors for rich text component [ALT-1216]

packages/core/src/utils/components.ts, packages/visual-editor/src/components/DraggableHelpers/ImportedComponentErrorBoundary.tsx, packages/visual-editor/src/hooks/useComponent.tsx
If the customer's code caused an error, our "ImportedComponentErrorBoundary" would transform it to another error which is not forwarded to the web app and thus not tracked in Sentry.
As this error boundary is wrapping every node on every level, it suppressed also errors coming from our own SDK code as they are getting wrapped by this boundary as well.
To ensure that we only forward errors that are caused by us, the deepest/ closest error boundary now differentiates between "Contentful component" and others. The error boundary of parent nodes will pass it on if it was already processed.
Imagine the following tree:
-> Section [SDK]
->> Custom Container with slots [Customer code]
->>> Button [SDK]
As we add the error boundary on every level, we can now catch any error directly after it was …
=> fix: dont suppress errors in SDK code but only custom code []

packages/core/src/constants.ts, packages/core/src/utils/breakpoints.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/core/src/utils/styleUtils/styleTransformers.ts, packages/core/src/utils/styleUtils/stylesUtils.ts, packages/visual-editor/src/hooks/useComponentProps.ts
Setting a design value like `cfTextItalic` to `false` for a certain breakpoint doesn't work as the conditional logic in the SDK would fall back to the next truthy value in the set of breakpoint values.
Only cascade through the breakpoint values if the value at hand is `undefined | null | ''`
=> fix: allow design value to be falsy for certain breakpoint [SPA-2391]

README.md, examples/next-app-router/README.md, examples/next-pages-router/README.md
1. Adds new relevant links to contentful.com developer docs. Removes the "Home" link as it's just a redundant collection of links (also included on every individual doc's navigation sidebar)
2. Fix links to point to `contentful.com` instead of `localhost`. Also link to NextJS doc for app/pages routers.
=> docs: update/fix links to CF dev docs

package-lock.json, packages/core/src/types.ts, packages/visual-editor/src/hooks/useCanvasInteractions.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts
Our SDK logic to immediately add a component to the local tree was incorrectly adding an assembly as a regular block on the initial render. This resulted in broken behavior where editor mode props were not passed properly to an assembly and therefore breaking DND.
This fix adds functionality so that we know if we are dragging an assembly type node during a component add action and if we are, we prevent the auto-creation of a block node.
Ticket: https://contentful.atlassian.net/browse/ALT-1220
Related user_interface PR: https://github.com/contentful/user_interface/pull/23249
=> fix: assemblies incorrectly rendered on initial drop [ALT-1220]

packages/core/src/__fixtures__/designTokens.ts, packages/core/src/utils/breakpoints.spec.ts, packages/core/src/utils/breakpoints.ts, packages/core/src/utils/styleUtils/ssrStyles.spec.ts, packages/core/src/utils/styleUtils/ssrStylesDesignTokenResolution.spec.tsx
Allow `getBreakpointByValue` to return raw design values without resolving design tokens
- When calling this method from the UI, we don't want design tokens to be resolved into values, because we want to design sidebar input to use the string template design token value in order to show the design token badge element.
- When this method is called from the SDK side, we do want any design token values to be resolved into css values
=> fix(core): resolving design values [ALT-1222]

.github/PULL_REQUEST_TEMPLATE.md
> [!TIP]
> 1. Use "Squash and merge" when merging changes into `development`.
> 2. Use "Create a merge commit" when releasing changes into `next` and `main`.
**Squash and Merge**: When merging feature branches into the `development` branch, prefer to use this merge setting to keep the history clean and focused. When a PR contains multiple commits, this setting will squash all commits into a single commit which provides a cleaner revert potential and easier git bisecting.
**Merge Commits**: When merging changes into the `next` and `main` branches, always use this merge setting to preserve the full history and context of changes, which is important for the publish workflow to handle versioning and generating change logs.
Github remembers your previous merge setting each time you merge a PR, …
=> chore: update PR template to include reminder when merging []

packages/core/src/utils/breakpoints.ts, packages/core/src/utils/styleUtils/ssrStyles.ts
Falsy breakpoint values like `false` or `0` would be currently not be rendered by our SSR logic.
We now check explicitly for values that are not supported/ empty. So far these are `null`, `undefined`, and empty strings.
Update:
I just found out that this was fixed [yesterday](https://github.com/contentful/experience-builder/pull/748) as well by @ChidinmaOrajiaku. If you agree, I will still add this change to allow `0` as well and explicitly rule out "empty values".
=> fix: allow rendering falsy breakpoint values in SSR [SPA-2375]

packages/core/src/fetchers/fetchAllEntities.spec.ts, packages/core/src/fetchers/fetchAllEntities.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/fetchers.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
Removes the `withoutLinkResolution` chain modifier so that any entries embedded into the fetched entry are resolved in its response. Fixes bug [ALT-1146].
This change also brings in line how the experiences are fetched in delivery and editor modes to be (a bit) more aligned. For instance, the call to fetch the entities in the UI included referenced entities up to 10 levels deep. The query was modified to add the "includes: 10" parameter so that querying the data in each place is more like the other.
[ALT-1146]: https://contentful.atlassian.net/browse/ALT-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: resolve fetched entities for experiences [ALT-1146]

packages/templates/nextjs-marketing-demo/src/components/CustomRatingComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/studio-config.ts
Get the Ant Customer Rating component into the template demo app https://ant.design/components/rate
=> [ALT-1246] feat: add custom rating to the marketing template

packages/templates/nextjs-marketing-demo/src/components/CardComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/studio-config.ts
Changes for the marketing demo app:
* Add design tokens to match the figma design
* Change the Card component to use a Slot for the cover (image) area
=> feat(nextjs-marketing-demo): add design tokens and card cover slot [ALT-1272]

packages/core/src/test/__fixtures__/entities.ts, packages/core/src/utils/transformers/media/transformMedia.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts
The image optimization code was expecting the component to have a cfWidth variable set, and error if it did not. Since the column component did not have cfWidth, it was erroring when trying to set the background image on a column.
When seeing if there is a cfWidth set, if there is not, we default to 100% width instead and let the user set a Target Width on the variable to help with optimization.
=> fix: default width to 100% when component doesn't have a width variable [ALT-956]

packages/components/src/components/Image/Image.css, packages/components/src/components/Image/Image.cy.tsx, packages/components/src/components/Image/Image.tsx, packages/core/src/utils/components.ts, packages/core/src/utils/index.ts, packages/core/src/utils/sanitizeNodeProps.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/blocks/preview/PreviewUnboundImage.tsx, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/hooks/useComponentProps.ts
Fixes a bug where the `width` style is being applied to both the wrapping div and element. 
This was especially noticeable when using percent widths on an Image component because the double-width makes the image half the expected size.
For editor mode, I updated `useCompnoentProps` to set the height and width to `100%` when those styles are applied to the wrapping div.
For delivery mode, I added a new `PreviewUnboundImage` component in the SDK.  This component replicates the same behavior as editor mode for the unbound image placeholder element. A wrapping is styled with the image component's height and width, and the placeholder element is styled with `100%` height and width to match the editor mode appearance.
https://github.com/user-attachments/assets/4d51edd4-1cb8-479c-a37c-c4c4ee6653c …
=> fix: width applied to both wrapping div and img [ALT-1293]

packages/core/src/definitions/styles.ts
Columns is set to margin `0 auto 0 auto` from the user_interface but the default is `0 0 0 0` in the SDK which results in the change indicator showing on initial drop of the columns component.
=> fix: columns uses incorrect default value []

examples/next-app-router/src/app/[locale]/[slug]/page.tsx, packages/templates/nextjs-marketing-demo/src/app/[locale]/[slug]/page.tsx, packages/test-apps/nextjs/src/app/[[...slug]]/page.tsx, packages/test-apps/nextjs/src/studio-config.ts
Design tokens were not being used for our internal apps on NextJS in SSR.
The config to register components and design tokens was only being called in client components, so when the CSS was generated server side, it was unable to look up the design tokens being used.
This PR updates the apps to also include the configuration file on server side pages as well as client side pages.
=> fix: update NextJS apps to import config server side so design tokens are registered [ALT-1314]

packages/components/src/components/Divider/ContentfulDivider.css, packages/components/src/components/Divider/ContentfulDivider.tsx, packages/components/src/components/Image/Image.tsx, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts
Fixes the Divider component after the changes in #778 caused a regression with the Divider's position
The Divider positioning issue was due to the Divider component having Margin on by default.  This issue was affecting any component that applies Margins and Relative height/width.
I updated the `useComponentProps` hook to apply the Margin styles to `wrapperStyles` while removing the Margin from the component via `overrideStyles` which positions the component correctly when mixing margins + relative height/width.
I adjusted the conditions in `useComponentProps` so that the `wrapperStyles` and `overrideStyles` will only be used when the hook is called with `requireDragWrapper: true` -- making sure that we aren't accidentally using `wrapperStyles` unless the wrapper is actually being used. …
=> fix: apply margin to wrapperStyles when drag wrapper is enabled [ALT-1293]

packages/visual-editor/src/components/DraggableBlock/styles.module.css
Bug where even if user set a pattern to 100% height, the editor did not show it as such
https://contentful.atlassian.net/browse/ALT-1294
patterns create both an assembly div and a child div of that for the assemblyBlock. AssemblyBlock has the styles the user selected for the pattern while assembly is mostly a wrapper and only had 100% width on it. If we add 100% height too then the user should see their styles as expected.
=> fix: make pattern height take 100% of available space [ALT-1294]

.husky/commit-msg, .husky/post-commit, .husky/pre-commit, package-lock.json, packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/components/DraggableHelpers/Placeholder.tsx
Fixes a bug where we couldn't drop or move a component between patterns or custom components.
Ticket: https://contentful.atlassian.net/browse/ALT-1230
Also fixes a styling bug with the blue placeholder so that it aligns properly in respect to flex direction of the parent element. 
Chore: cleanup husky configs for v10
https://github.com/user-attachments/assets/0be6624a-b764-4292-982e-4802f4bc2e59
=> fix: dnd between custom components and patterns [ALT-1230]

packages/core/src/constants.ts, packages/core/src/definitions/styles.ts, packages/core/src/types.ts, packages/core/src/utils/styleUtils/stylesUtils.ts
Adds new cfFlexReverse property that is used to toggle the flex-direction to reverse for a component.
Ticket: https://contentful.atlassian.net/browse/ALT-1277
Related UI PR: https://github.com/contentful/user_interface/pull/23667
=> feat: add new cfFlexReverse built in style property [ALT-1277]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators/tests/componentSettings.spec.ts
Removed the check that triggered a custom error when both fields were spotted within the same entity
=> feat: allow componentSettings and usedComponents fields within the same entity [SPA-2426]

.github/workflows/vercel.yaml, package-lock.json, packages/components/src/components/Heading/index.ts, packages/test-apps/react-vite/package.json
This is a small change that has annoyed me for a long time.
The real purpose for making this change is I want to kick off a fresh deployment for the react-vite test app in vercel to see if it will update the SDK for this hosted app running in prod.
=> fix: update display name for text variable in the Heading component []

packages/core/src/types.ts, packages/templates/react-vite-ts/.gitignore, packages/test-apps/react-vite/src/studio-config.ts, packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts
This is a fast follow change for #800 to rename the `editorWrapperWidth` option to `wrapContainerWidth` so its consistent with the other options like `wrapComponent` (boolean) and `wrapContainer` (react element)
=> fix: rename editorWrapperWidth option to wrapContainerWidth [ALT-1358]

package-lock.json, packages/visual-editor/src/components/DraggableBlock/styles.module.css
You can not drop nodes in empty nodes with `children:true` as they are invisible by default. Problem is that they have a width of `0px` if the customer doesn't define it otherwise.
Add a minimum width similar to the height.
https://github.com/user-attachments/assets/9bae3cf3-8293-4344-b67e-7c0517eb8125
https://github.com/user-attachments/assets/ccf1b0d3-9473-47fa-9858-c69550025d34
=> fix: add min width 80px for dropping children in empty containers []

packages/visual-editor/src/hooks/useComponentProps.ts, packages/visual-editor/src/hooks/useEditorModeClassName.spec.ts, packages/visual-editor/src/hooks/useEditorModeClassName.ts
When [this SDK error](https://contentful.sentry.io/issues/6019374985/?alert_rule_id=15048860&alert_type=issue&notification_uuid=5d6c2561-db7c-47ce-a2d7-ef5ebaf293b5&project=8049&referrer=slack) popped up today, I started looking into the code where this error originated from. It seems like, we recreate the styles too often.
In `useComponentProps` we re-create the styles map `componentStyles` on every render which in turn will add them to the DOM again and again on every render. I added a `useMemo` to only regenerate the styles map when necessary and there save us from changing the DOM styles on every render.
Additionally, I improved the logic `useEditorModeClassName` to clean up old styles if they are not used anymore. This is only relevant to nodes without IDs which theoretically …
=> fix: improve performance of styles generation []

packages/components/src/components/Button/Button.tsx, packages/components/src/components/Divider/ContentfulDivider.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts
We're getting this warning when rendering dividers in the canvas. This is because, we're not using `withComponentWrapper`. I'm not sure why but that might be something that @ryunsong-contentful could answer as I don't have context on the creation of the divider.
=> fix: handle leaking dragProps []

packages/components/src/components/Button/Button.css, packages/components/src/components/Button/Button.tsx
When the label value of a button is empty (explicitly set via manual binding tab), the button rendered as a small square.
To ensure that the button always renders in the correct height with a normal line height, we add a pseudo element when it's `:empty`
=> fix: dont shrink button height when empty [SPA-2459]

packages/core/src/definitions/styles.ts
As we're using the description field for boolean content properties, the hyperlink behaviour is now having the correct description "Open in new tab"
=> fix: use the correct description for hyperlink behaviour property [SPA-2398]

packages/visual-editor/src/components/DraggableBlock/styles.module.css
This css change makes it so moving a pattern on the canvas will activate the dropzone hitboxes more reliably.
While debugging the issue, I noticed that the `e.target` in `VisualEditorRoot` was constantly reporting the `DraggableClone` element as the mouse move target, which would then fail to find a closest Dropzone element to the Clone. This would only happen when moving a Pattern on the canvas.
https://github.com/contentful/experience-builder/blob/5057733477861701f2ec6fc06cb16f36c0b0333d/packages/visual-editor/src/components/VisualEditorRoot.tsx#L30
I noticed when dragging a Pattern and quickly moving my mouse back and forth over the Dropzone container, the mouse pointer position would desync and "breaks free" from the Clone element's position, and then the `e.target` would successfully …
=> fix: dropzone hitboxes when moving patterns on the canvas [ALT-1391]

packages/core/src/definitions/styles.ts
Changes the Container and Columns default margin value back to `0 0 0 0` and added a comment to mention that the UI overrides the value to `0 Auto 0 Auto` when these components are added at the root/top-level
=> fix: change container/columns default Margin value [ALT-1388]

packages/experience-builder-sdk/src/hooks/useClassName.spec.ts, packages/test-apps/react-vite/src/App.tsx, packages/test-apps/react-vite/src/Page.tsx
You can now use the locale as URL param with the vite test app by defining the following preview URL:
`http://localhost:5173/{locale}/{entry.fields.slug}`
It will still support the previous version as well.
=> test: add optional locale param to react-vite test app [SPA-2467]

packages/core/src/fetchers/fetchAllEntities.spec.ts, packages/core/src/fetchers/fetchAllEntities.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/test/__fixtures__/entities.ts, packages/core/src/utils/transformers/getArrayValue.ts, packages/core/src/utils/transformers/getResolvedEntryFromLink.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts, packages/core/src/utils/transformers/transformBoundContentValue.ts, packages/core/src/utils/transformers/transformRichText.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
We have several instances where if we bind an entry to a component variable, any referenced entities in that entry are not resolved, and therefore not available as a passed in prop to the component.
Instances where this can occur:
An entry bound into a rich text field
An entry bound to another entry that itself has references to another entry
A list of entries/assets bound to an array variable type where some of which could have references as well
Pretty much any case where a bound entity would have a reference to another entry.
Initially, this was attempted to be solved by removing the `withoutLinkResolution` call to the fetch entities API. This automatically resolved any referenced entries no matter how they were referenced. However, this caused issues elsewhere, so we had to do this …
=> feat: resolve entries that are embedded into bound entries [ALT-1368]

examples/astrojs-ssr/package-lock.json, examples/astrojs-ssr/package.json, examples/next-app-router/package-lock.json, examples/next-app-router/package.json, examples/next-pages-router/package-lock.json, examples/next-pages-router/package.json, package-lock.json
Updating the example apps to use the latest version of the Experiences SDK.
I tested all 3 apps running locally while connected to my Prod space and everything seems to work well.
=> chore: bump sdk version in example apps []

packages/experience-builder-sdk/src/hooks/useFetchById.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.ts
https://contentful.atlassian.net/browse/ALT-1447
Removed the client from useEffect dep arrays so it wouldn't cause issues changing. This should be a safe change since the client doesn't typically change during the request.
=> fix: don't add client object to fetchBy dependency arrays to fix infinite rerenders [ALT-1447]

packages/visual-editor/src/store/tree.ts
When testing initialisation with custom breakpoints for [this fix PR](https://github.com/contentful/user_interface/pull/24124#issuecomment-2486324029), I realised that the diffing logic will ignore breakpoint changes if the tree didn't change.
Even if the tree is empty (and thus an empty tree diff), we accept a change of the breakpoint settings.
=> fix: react on changes of breakpoint when tree is the same [SPA-2487]

packages/core/src/utils/transformers/media/transformMedia.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts, packages/core/src/utils/utils.ts
Previously the css url for the background image would ignore the target width, but now setting the target width appropriately changes the background image url when its value is less than the asset width.
https://github.com/user-attachments/assets/687bc2d0-529a-4121-b9e8-3654ea071c94
=> [ALT-1308] fix: target width now applies the background image url css properly

packages/core/src/types.ts
Exporting `ComponentDefinitionVariableTypeMap` (a new type that was recently added in #850) so that we can have it available to use in the UI as well.
=> fix(core): export new type for ComponentDefinitionVariableTypeMap [ALT-690]

packages/core/src/utils/styleUtils/ssrStyles.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators/tests/componentTree.spec.ts
A few upcoming features (e.g. diffing between the component tree for version history) would benefit from a stable UUID-style identifier for tree nodes that's persisted and (relatively) stable throughout the lifetime of that node.
* Add a new `id` property to the validator for the component tree node schema, on the current schema version
For now we decided against creating a new schema version to introduce this property. This can come later, once the implementation is stabilized and we introduce code that ensures that old versions of experiences (ie that use the current schema version) can be seamlessly upgraded to the new version correctly.
=> feat: add optional id property for component tree nodes

package-lock.json, packages/core/src/types.ts
Reverting changes to the value type in `ValidationOption` (the validation rules of component definition variables)
I tried to make this type smarter and infer the right type based on the variable type, but it's actually not a good idea to do this because the validation rules are only expected for certain variable types as simple string or number values in the UI side, so it's best to leave this type as it was before.
Eventually we could expand the support for validations on other variable types and that would be a better time to revise this type.
=> fix: revert type for validation option values [ALT-690]

examples/astrojs-ssr/src/components/Experience.tsx, examples/astrojs-ssr/src/getExperience.ts, examples/next-app-router/src/getExperience.ts, examples/next-pages-router/src/getExperience.ts, packages/core/src/fetchers/fetchById.spec.ts, packages/core/src/fetchers/fetchById.ts, packages/core/src/fetchers/fetchBySlug.spec.ts, packages/core/src/fetchers/fetchBySlug.ts, packages/experience-builder-sdk/src/index.ts, packages/templates/nextjs-marketing-demo/src/getExperience.ts, packages/test-apps/nextjs/next-env.d.ts, packages/test-apps/nextjs/src/utils/getExperience.ts
Added an optional param named isEditorMode to the vanilla js fetchers (fetchBySlug and fetchById) to be a noop if it is true. This will help clean up code in customers apps that they would otherwise have to write themselves. Now they just need to pass in if they are in editor mode or not to the function.
Also updated the Next and Astro test apps/examples to use this new method.
=> feat: add isEditorMode param to vanilla js fetchers []

packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/components/DraggableBlock/Tooltip.tsx
This change prevents the visual editor's hover tooltip from displaying when hovering on the selected component.
=> fix(visual-editor): prevent hover tooltip for selected component [ALT-1090]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx
Fixed an issue in `CompositionBlock` where `cfSsrClassName` was being set to `undefined` when `getPatternChildNodeClassName` was not defined. Added checks to ensure `getPatternChildNodeClassName` exists before calling it, ensuring SSR class names are applied when rendering components in preview/delivery.
For internal tracking: https://contentful.atlassian.net/browse/ZEND-5755
=> fix(experience-builder-sdk): SSR classNames not being attached to components rendered in SSR [ZEND-5755]

packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useBreakpoints.ts
As a regression of https://github.com/contentful/experience-builder/pull/874, the application would crash everytime when `cfSsrClassName` was not defined, i.e. when not running in SSR.
Simplify the ternary conditions and remove some duplicate conditional checks. As `resolveDesignValue` handles undefined values, I adjusted its types and was able to further reduce our conditional logic in `CompositionBlock`.
=> fix: render patterns in preview [SPA-2518]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators/tests/componentTree.spec.ts
Enforces a stricter schema for the `id` property of component tree node.
In https://github.com/contentful/user_interface/pull/24351 we introduced a change to persist component tree node ids in experiences and patterns. As part of that change -- mostly to ensure payloads were manageable in size -- we introduced a shorter key length and more constrained alphabet.
This PR aligns the experience schema with that change.
* Introduce a new schema for the id instead of modifing the existing uuid schema. That schema is used elsewhere -- and additionally the new schema is not really a uuid.
* Export the schema so that it can be referenced directly elsewhere (this allows us to remove some hard coding in tests in the web app)
There was a small learning related to the parallel tree representations we …
=> feat: add more strict id schema for component tree node

package-lock.json, packages/core/package.json, packages/core/src/test/__fixtures__/entities.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts, packages/core/src/utils/transformers/transformRichText.ts, packages/experience-builder-sdk/package.json, packages/test-apps/nextjs/src/components/KitchenSink.tsx, packages/test-apps/react-vite/src/components/KitchenSink.tsx
[ALT-1493] - when hyperlink to an asset or entry in a rich text field and binding it to a rich text variable in studio, the entities where not being resolved.
[ALT-1493]: https://contentful.atlassian.net/browse/ALT-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: hyperlinks to assets or entries should resolve in a rich text variable [ALT-1493]

packages/components/src/components/Heading/index.ts, packages/components/src/components/Text/index.ts
The `as` variable for the Text built-in component and the `type` variable for the Heading built-in component should be moved to the design tab and have the display name changed to `HTML tag`
Ticket: https://contentful.atlassian.net/browse/LUMOS-482
NOTE:
This has been tested and it does not break existing experiences that have content bound to these variables. Even though the variable is moved from the content to the design tab, previously set values (whether a bound entry, asset, or manual text) are persisted. When the value is changed from the design tab, it still works as expected.
Text component
Heading component
=> chore: rename and move variables to design tab for text and heading [LUMOS-482]

packages/components/src/components/Text/Text.css, packages/components/src/components/Text/Text.cy.tsx, packages/components/src/components/Text/Text.tsx
This change fixes an issue with the text alignment when a URL is bound to a built-in Text component.
Editor:
Delivery:
=> fix(components): add className to anchor tag when passing url to the Text component [ALT-1522]

package-lock.json, packages/experience-builder-sdk/package.json
There was a vite plugin in the experiences-react-sdk package that was being registered as a regular dep (where it should of been a dev dep). Therefore, the plugin and all its dependencies where being installed in apps that didn't need it. 
Closes #904 
Moved the dep to dev deps. We should consider removing altogether (as I don't think its used at the moment), but this was the safest option.
=> fix: move vite-plugin-css-injected-by-js plugin to dev deps [#904]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.spec.tsx
Adding tests for `<CompositionBlock>` to verify the SSR class name is set as expected when rendering components.
=> chore(experience-builder-sdk): add tests for SSR classnames [ALT-1509]

packages/core/src/utils/styleUtils/styleTransformers.ts
Let visibility display style take precedence when toggled
Following Amr discovery in the video below, some components have inline display which overrides the transform visibility `display: none` 
Bug Video
https://github.com/user-attachments/assets/8ab30fb0-fca9-4c1b-8feb-977944bc0a35
This PR ensures the transform visibility `display: none` takes precedence when the value is false
Fix after PR
https://github.com/user-attachments/assets/67f96e78-cbdf-409d-92e0-aa580c5a0e46
=> fix: let visibility display style take precedence when toggled [SPA-2468]

packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx, packages/visual-editor/src/components/DraggableBlock/DropzoneClone.tsx, packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/components/DraggableBlock/EditorBlockClone.tsx, packages/visual-editor/src/components/DraggableHelpers/CircularDependencyErrorPlaceholder.tsx, packages/visual-editor/src/hooks/useComponent.spec.ts, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/utils/getTreeDiff.ts
When accidentally causing a loop in the chain of pattern dependencies, the SDK would crash and the browser tab becomes not responsible.
To address this, we want to render a similar error as we do for missing component definitions. To detect a loop during the render cycle, we pass through a list of `wrappingPatternIds` that gets extended when "diving into" a pattern node.
To detect the loop as early as possible (and not pollute the canvas with multiple instances of a single pattern), we have to know the ID of the opened experience ID. When finding the same ID again deeper inside the tree, we stop immediately the rendering cycle and render the error message. To know the global experience ID, we leverage the `blockId` of the root node. So far, it was the same as the root node id. Using this …
=> fix(visual-editor): handle circular pattern dependencies in the tree [SPA-2511]

packages/components/src/components/Button/index.ts, packages/components/src/components/Heading/index.ts, packages/components/src/components/Image/index.ts, packages/components/src/components/RichText/index.ts, packages/components/src/components/Text/index.ts, packages/core/src/definitions/styles.ts
https://www.figma.com/design/pjrHiK6yw0eIWwtQ4Zzvnn/Studio-Content-Binding?node-id=878-109152&t=PPoR63zgphoihGfy-1
As titled
a. **URL** is restricted to `Entry`, `Experience`, `Manual`
b. Background image is restricted to `Asset`, `Entry`, `Manual`
a. **URL** is restricted to `Entry`, `Experience`, `Manual`
b. Background image is restricted to `Asset`, `Entry`, `Manual`
a. Background image is restricted to `Asset`, `Entry`, `Manual`
a. Background image is restricted to `Asset`, `Entry`, `Manual`
a. **Label** is restricted to restricted to `Entry` and `Manual`
b. **URL** is restricted to `Entry`, `Experience`, `Manual`
a. Text is restricted to `Entry` and `Manual`
b. URL is restricted to `Entry`, `Experience`, `Manual`
a. Alt Text is restricted `Asset`, `Entry` and `Manual`
b. Image is …
=> [LUMOS-507] feat(content binding redesign - sensible defaults): add bindingSourceType validations to built in components

packages/core/src/entity/EntityStore.ts, packages/experience-builder-sdk/src/hooks/useDetectCanvasMode.tsx, packages/experience-builder-sdk/src/hooks/useFetchByBase.ts, packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx
I often run into this error after hitting "save" on the editor:
I discovered that the detected canvas mode would not switch to `editor` in time (we wait only 100ms). This triggered the query to CPN which eventually ends in an error. As a fix, we're handling a "too late" event for requesting editor mode. In that case, we ignore the result of the API query and just do business as usual.
@ethan-ozelius-contentful we might want to revisit the current timeout of 100ms. As this could change multiple times back and forth via trial & error, I decided to implement a graceful handling of the race condition.
=> fix(experience-builder-sdk): remove race condition in mode detection when reloading the canvas on save [SPA-2511]

packages/core/src/fetchers/fetchById.ts, packages/core/src/fetchers/fetchBySlug.ts, packages/core/src/fetchers/shared/circularityCheckers.spec.ts, packages/core/src/fetchers/shared/circularityCheckers.ts
When creating a hyperlink that points to the experience entry itself, this breaks SSR applications preview/ delivery mode.
Similar to the circularity check for `usedComponents`, circular references are replaced by a plain link.
=> fix(core-fetchers): remove circular self references [SPA-2557]

packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/fetchReferencedEntities.ts
When fetching entries and assets based on the `dataSource`, we're not properly handling the case of entries or assets being used multiple times. While this is quite common, we're currently not storing experiences in such an "efficient" way to only have one data source for all its occurrences. So for the time being, we have to accept that there are duplicates.
To not create extremely long query strings, a set is used instead of a plain list to collect all IDs before fetching the entities.
Example where an ID is used twice for the `sys.id[in]` filter:
=> fix(core-fetchers): remove duplicate entry IDs from API query [SPA-2559]

packages/experience-builder-sdk/src/hooks/useBreakpoints.ts
When switching with dev tools between desktop and mobile emulator, the breakpoint-specific values would not update correctly.
I noticed that we recreate the event listeners for this on every single render cycle. This led to some changes being not handled correctly as the event listener was not ready yet.
We fix this now with a editor-similar approach
=> fix: dont recreate mediaQuery matchers on every render

package-lock.json, packages/core/src/types.ts, packages/validators/src/schemas/index.ts, packages/validators/src/schemas/v2023_09_28/experience.ts
Update the validator's package so that we can begin saving prebinding data to both patterns and experiences.
Ticket: https://contentful.atlassian.net/browse/LUMOS-495
NOTE: this is just to get us started, an additional ticket exists to finalize the field names in the validators package once they have been set. https://contentful.atlassian.net/browse/LUMOS-523
=> chore(pre-binding): update validators for prebinding fields [LUMOS-495]

packages/validators/src/schemas/v2023_09_28/experience.ts
Additional changes to the validators package so that we can build the initial rendering logic for pre-bound patterns on experiences.
Ticket: https://contentful.atlassian.net/browse/LUMOS-543
=> chore: update validators for pre-binding functionality [LUMOS-543]

packages/experience-builder-sdk/src/core/componentRegistry.ts
A customer was losing all their content when saving an experience with a pattern in it. This is due to the fact the SDK defines an empty definition without variables and sends it to the editor. When saving the experience this placeholder definition will make all the content vanish from the tree.
=> fix: dont send pattern definitions to the editor [SPA-2588]

packages/components/src/components/Divider/ContentfulDivider.css
The pseudo element covers many other neighbouring components in delivery. This is why we disable it when the DND context doesn't exist (i.e. delivery mode).
=> fix(divider): remove the CSS overlay of divider component in delivery  [SPA-2596]

packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx, packages/visual-editor/src/components/RootRenderer/render.module.css
This change adds a small invisible spacer element to the bottom of the canvas when dragging in a new component.
First I experimented with reusing the `<EmptyContainer>` ("Add components to begin" placeholder) as the last element on the canvas, but it had some issues with overlapping dashed outlines and not shifting position when a canvas interaction shows a hitbox that causes other elements to shift positions. I also thought it seemed a little too busy with the extra "Add components" placeholder element.
I tried a simpler approach and added an absolute positioned invisible div at the bottom of the canvas. This spacer element only renders when the user is dragging. Since it's absolute positioned, if the user has static content below the ExperienceRoot (such as a footer) the spacer element …
=> feat: add buffer space to bottom of canvas [LUMOS-549]

packages/core/src/utils/breakpoints.spec.ts, packages/core/src/utils/breakpoints.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.spec.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useBreakpoints.spec.ts, packages/visual-editor/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useComponent.spec.ts, packages/visual-editor/src/hooks/useComponentProps.spec.ts
Makes sure that active breakpoint is updated correctly when breakpoints as eventually updated.
**Fix 1**
The root of the problem was that initial state is only used on the first render (see also this [SO question](https://stackoverflow.com/questions/58818727/react-usestate-not-setting-initial-value)), but in the first render we'll always pass in `breakpoints: []` which leads to `mediaQueryMatches` being empty. On the next render when breakpoints have been fetched this line doesn't actually update the `mediaQueryMatches`:
```
const [mediaQueryMatches, setMediaQueryMatches] =
useState<Record<string, boolean>>(initialMediaQueryMatches);
```
We need to instead update the `mediaQueryMatches` inside the useEffect [here](https://github.com/contentful/experience-builder/pull/995/files#diff-c71237e …
=> fix: update active breakpoint correctly

packages/visual-editor/src/hooks/useSingleColumn.ts
Handle case where single column is not wrapped inside a `Columns` component.
An error is thrown when a `Column` component is not wrapped inside a `Columns` component. This shouldn't normally happen but a customer has run into this scenario and the editor is crashing in this case:
Column tree node:
Parent tree node (it's a `contentful-section` instead of `contentful-columns`):
=> fix: handle case where single column is not wrapped in columns component

packages/validators/src/schemas/v2023_09_28/experience.ts
Add validation for thumbnail ids
These are the thumbnails we are providing for now and these could increase in the future
=> chore: add thumbnail id to component settings validation [SPA-2572]

packages/core/src/types.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/types.ts
Allow us to more easily derive the contentType for prebinding by including it in the schema stored on the entry instead of trying to derive at runtime with the fetched entity.
Ticket: https://contentful.atlassian.net/browse/LUMOS-561
=> chore(prebinding): add contentType to patternPropertySchema

packages/core/src/types.ts, packages/experience-builder-sdk/src/utils/withComponentWrapper.tsx, packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts
We added the prop `isInExpEditorMode` as some customers want to render different content in editor mode than in delivery.
However, this will cause a React warning for every (non-structural) component.
To still allow this level of customization without disrupting simple use cases, we only provide it if activated through the registration options.
I noticed that we still have two options that have no effect anymore on the SDK. I removed those (`wrapContainerTag` and `wrapContainer`)
=> feat: only provide isInExpEditorMode if activated in options [SPA-2607]

package-lock.json, packages/core/src/types.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/types.ts
In order to have prevent dependabot from overriding prerelease versions of the SDK that is compatible with prebinding, we need to merge in the latest schema changes of this feature branch so we can release production version of the SDK. 
Otherwise, we see regressions in the content_api and typings in the user_interface when dependabot updates to an incompatible version.
=> feat(prebinding): schema updates and rendering of prebinding mappings in delivery mode

packages/components/src/components/Heading/index.ts
LUMOS-578
Remove the `bindingSourceType` validation from the Text component.  Now Text can be bound to any binding source type: `entry`, `asset`, `experience`, `manual`.
=> [LUMOS-578] fix(text-component): add asset and experience to binding-source-type validation

packages/validators/src/schemas/v2023_09_28/experience.ts
Add `contentType` to the default entry field of a pattern property definition
=> chore(prebinding): update schema for default entry to include contentType [LUMOS-581]

packages/core/package.json, packages/experience-builder-sdk/src/index.ts, packages/templates/nextjs-marketing-demo/src/components/ButtonComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/components/CardComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/components/RatingStarsComponentRegistration.tsx
Ensure that types are properly exported so that they are provide hints/autosuggestion when writing component registrations.
Additionally export `ComponentRegistration` type as it seems to be more useful than `ComponentDefinition` when defining components.
I noticed that when hovering over an import of `'@contentful/experiences-core/constants'` or `'@contentful/experiences-core'` in the `experiences-sdk-react` built version, visual studio was able to resolve and follow the path of those files unlike the `'@contentful/experiences-core/types'`
https://github.com/user-attachments/assets/b1b152ae-1bbb-4456-9b28-702071b49e78
This seemed to be the reason it couldn't resolve types for `ComponentDefinition` and `ComponentRegistration`.
After adding `./types` in the `exports` of the core package …
=> fix: types export from core package [SPA-2612]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators/tests/componentSettings.spec.ts
Add the optional `category` property that can be stored in `componentSettings` of patterns. This should allow us to group them better in the sidebar.
I took the liberty to set the max width to 50 characters. Also, I added tests validating the `thumbnailId` that was missing for an unknown reason
=> feat: add an optional category field to componentSettings [SPA-2632]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/validators/tests/componentSettings.spec.ts
Add the optional category property that can be stored in `componentSettings` field of pattern entries. This should allow users to group them better in the sidebar.
=> feat: add an optional category field to componentSettings (#1027)

packages/validators/src/schemas/v2023_09_28/experience.ts
Modifies the defaultValue of patternPropertyDefinitions to remove the need for using `dataSource` on a pattern entry and directly link the entry in the defaultValue.
Ticket: https://contentful.atlassian.net/browse/LUMOS-594
=> chore(prebinding): modify schema to support entity link directly on defaultValue [LUMOS-594]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/test-apps/nextjs/src/components/CustomButton.tsx, packages/test-apps/nextjs/src/studio-config.ts
Removing the key overwrite after a use effect as we have fixed the breakpoint update.
This is where the useEffect was introduced: https://github.com/contentful/experience-builder/pull/979
=> fix: remove the key update via the use effect []

packages/core/src/utils/debug.ts, packages/core/src/utils/debugLogger.spec.ts, packages/core/src/utils/debugLogger.ts, packages/core/src/utils/index.ts, packages/experience-builder-sdk/src/ExperienceRoot.tsx, packages/experience-builder-sdk/src/index.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.ts, packages/experience-builder-sdk/src/window.d.ts, packages/test-apps/nextjs/src/app/[[...slug]]/page.tsx, packages/test-apps/nextjs/src/components/Experience.tsx
Adds support for debug logger in experiences SDK.
Adds support for debug logger in experiences SDK. Debug logger is disabled by default. There are two ways to enable the logger:
1. By passing a `debug` prop to the `ExperienceRoot`.
This is useful for server side rendering use-cases and cannot be changed during runtime.
2. By calling `window.__EB__.enableDebug()` method during runtime.
When calling this method, we also set `cf_debug` key in localStorage. This is to preserve the state of the logger through a page refresh.
Logger can be disabled by calling `window.__EB__.disableDebug()` 
Note that the `debug` prop will take precedence so if it's passed the `window.__EB__` methods won't be able to override it.
Here is an example when using Client Side Rendering (using method 2.): …
=> feat: add support for debug logger [SPA-2589]

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-ssg/package-lock.json
This should address security vulnerabilities reported by dependabot for the following packages (all transitive dependancies of gatsby):
* loader-utils
* semver
* yaml
These are only used on an example app, so they are not super critical but maybe we need to find a way to exclude them from the security report (or figure out if it's possible for dependabot to automatically update them too)
=> chore: bump vulnerable gatsby dependancies []

.github/workflows/publish.yaml
This is an attempt to force lerna to generate changelog from the last stable version. 
Right now the problem is that, on the last step of releasing the package when merging to `main` we instruct lerna to generate a changelog using the `--conventional-commits` argument. This generates the changelog but updates it with placeholder text like:
This is because lerna will use commits between the latest version and the last beta version, e.g. `v1.34.1-beta.0..v1.34.1`. But this diff doesn't include any meaningful commits, e.g.
In reality what we need is the diff `v1.34.0..v1.34.1`
It seems that lerna is using the git tags for this comparison, so if we don't generate tags for the prerelease versions then the changelog will compare with the last stable version. This is a solution suggested in the …
=> chore: use --git-tag-command to override lerna version tag for prereleases

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/main.yml, .github/workflows/publish.yaml
We no longer use a private npm.js registry (we're using the GH one). Also build and check steps don't require access to private registries.
=> chore: remove reduntant private NPM registry authentication

packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts
adds check for `cfVisibility` when generating wrapper styles. 
This bug (and this logic from `useComponentProps`) only applies to packages/visual-editor, when breakpoints always have current one (eg. defined via `useBreakpoints`  and `resolveDesignValue()` )
Within tests, it is important that component definition contains `cfVisibility` property. Otherwise iteration won't work.
=> fix: hiding nodes bug [SPA-2656]

.github/workflows/main.yml
After #1068 main.yml is throwing an error because of the leftover NPM_TOKEN. This PR fixes that.
=> chore: remove leftover NPM_TOKEN that breaks main.yml

packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx, packages/visual-editor/src/components/DraggableBlock/styles.module.css
I recorded the video with the explanation, but as it's a public repository, I won't attach it here.
Find it [here](https://contentful.slack.com/archives/C01R9P3CBH7/p1743760799219389?thread_ts=1740556729.913469&cid=C01R9P3CBH7) instead
Basically if the pattern's wrapper component doesn't have the `100%` height, then the dropzone component in the editor mode also shouldn't have it.
=> fix: pattern wrapper height to 100% only when the main component has 100% height [SPA-2580]

packages/test-apps/react-vite/src/components/ComponentUsingReferences/ComponentUsingReferences.module.css, packages/test-apps/react-vite/src/components/ComponentUsingReferences/ComponentUsingReferences.tsx, packages/test-apps/react-vite/src/components/ComponentUsingReferences/index.ts, packages/test-apps/react-vite/src/studio-config.ts
So far, we had no example where a component would render content from a content that is linked through a reference field of an entry.
When using the type `Link` for a variable definition, it allows binding to the whole reference field so the rendering code can pick up any fields from that referenced entity.
We adjusted the fetching logic in the user interface recently for that use case and now add an example use case.
https://github.com/user-attachments/assets/85fad642-8de4-43fe-a1ce-b2f3e62364c7
=> feat(test-apps/react-vite): add new component with Link field for testing [SPA-2692]

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json
Addressing one more vulnerability - path-to-regexp. I had to set an override for it as gatsby pins the version to 0.1.10.
=> chore: address path-to-regexp vulnerabilities

packages/create-contentful-studio-experiences/package.json
Added originally [here](https://github.com/contentful/experience-builder/commit/4495c1e1f98d6b1c66d54f003d8b2d21867f0f08#diff-ff10ee50b08de281bf55bbc3ff00039a12ab5d873341ee2c9f0562a807baacf0) and removed [here](https://github.com/contentful/experience-builder/pull/676/files#diff-7be23c66a973d29dddba6d84d4202a23810f186390de0ae10e17c400284c7e2cL22).
Caused pipeline failure since [this PR](https://github.com/contentful/experience-builder/pull/1068/files).
=> fix: publish create package to github registry [SPA-2729]

packages/components/package.json, packages/core/package.json, packages/create-contentful-studio-experiences/package.json, packages/experience-builder-sdk/package.json, packages/validators/package.json, packages/visual-editor/package.json
For some reason we have a version conflict.
Probably because the main branch failed the last times, it didn't bump the version correctly in next & development. here I'm manually bumping it now.
=> chore: resolve version conflict [SPA-2729]

packages/core/src/entity/EntityStoreBase.ts
Temporarily, we remove the logic error and let the automatic reference resolution be applied.
Later, we plan to release a major version of the SDK, where we remove automatic link resolution and instead will provide a tool to resolve the entities via a provided utility (synchronously).
The reason why we need to make such a change is that we don't want to set an expectation that the SDK will resolve all references. We pre-fetch only up to 3 levels of entities and stop at that level, while the current approach makes an impression that references are resolved all the time automatically.
Since it's going to be a breaking change, we will release it as such in a later version.
=> fix: not throw logic error if a resolved entity was detected [ZEND-6229]

packages/core/src/utils/styleUtils/styleTransformers.ts, packages/visual-editor/src/hooks/useSingleColumn.ts
When testing columns wrap count, I first assumed this was handled in the SDK and debugged the code in `useSingleColumn` (the only place referring this variable). Only after some log debugging, I figured this is solely handled in the web app by setting the `columnsSpan` accordingly so there was no work necessary in the SDK.
However, I found that we run some logic in here for every node that is never used which is why I removed that part form the hook.
=> fix: remove unused variable from useSingleColumn hook [SPA-2738]

packages/components/src/components/Image/Image.css, packages/components/src/components/Image/Image.tsx
The placeholder icon is aligned through absolute positioning. As there was not relative wrapper directly above it, it would be rendered out of bounds in some scenarios.
=> fix: add relative position wrapper for misaligned image placeholder [SPA-2764]

packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/visual-editor/src/store/editor.ts, packages/visual-editor/src/utils/treeHelpers.ts
I noticed some logic in the SDK that wasn't used at all while scanning the code.
=> refactor: remove unused code dragging and tree diffing [SPA-2610]

packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.ts, packages/experience-builder-sdk/test/__fixtures__/assembly.ts
Setting the design value for one specific breakpoint on a pattern instance, should not vanish the default value for other breakpoints.
Merge design values by breakpoint.
Based on top of https://github.com/contentful/experience-builder/pull/1125
=> fix: merge override and default design values by breakpoint in CSR preview [SPA-2602]

.github/workflows/main.yml, .github/workflows/publish.yaml
This uses the same publishing logic as for `development` but uses the `alpha` tag instead of `dev`.
Also, we try to keep it up to date with `development` by an automatic rebase. This might fail depending on the changes made on both sides, so I wrapped the `rebase` command to not make the pipeline indicate a failure.
=> chore: keep new v3-prerelease branch up to date and publish as alpha version [SPA-2745]

packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts, packages/core/src/utils/transformers/media/transformMedia.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.spec.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.ts, packages/visual-editor/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useComponentProps.ts, packages/visual-editor/src/hooks/useDropzoneDirection.ts, packages/visual-editor/src/hooks/useSingleColumn.ts
I noticed that `resolveDesignValue` required the `variableName` parameter while that was only used in very special cases, i.e. when it's a built-in property that supports design token. 90% of the cases passed explicitly a string that didn't match that condition. In those cases, we can also leave out the ignored parameter.
Make the `propertyName` argument optional and adjust all the places that passed a name that had no effect.
=> style: simplify resolveDesignValue by dropping the unused name arg [SPA-2610]

packages/experience-builder-sdk/src/core/sdkFeatures.ts
We will remove all dnd related code from the SDK. To allow a smooth transition, there is a new branch `v3-prerelease`. All dnd related code will be removed from the codebase in this branch.
To indicate to the web app that this SDK version supports the new native dnd handling, a new SDK capability is added called `nativeDnd`. The name might not be self-explanatory, so I added a comment as well.
=> feat: introduce SDK capability dndMigration [SPA-2745]

package-lock.json, packages/core/src/types.ts, packages/validators/package.json, packages/validators/src/schemas/componentDefinition.ts, packages/validators/src/schemas/index.ts, packages/validators/src/schemas/latest.ts, packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experience.ts, packages/validators/src/types.ts, packages/validators/src/validators/tests/componentSettings.spec.ts, packages/validators/src/validators/tests/experienceValidator.spec.ts, packages/validators/src/validators/tests/patternValidator.spec.ts, packages/validators/src/validators/validateBreakpointDefinitions.ts, packages/validators/src/validators/validateExperienceFields.ts, packages/validators/src/validators/validatePatternFields.ts, packages/validators/vite.config.mts
Split the validation schema for experience and pattern such that each can be validated independently.
Effort has been made to avoid any breaking changes. This includes re-exporting things from their original location and making the experiences validator call the pattern validator if it detects a pattern. Any potential breaking change found during review (including typing) should be flagged.
A common file has been created to reuse common schemas and reduce duplication.
https://contentful.atlassian.net/browse/SPA-2753
=> SPA-2753: split schema between experience and patterns

packages/visual-editor/src/components/RootRenderer/sendCanvasGeometryUpdatedMessage.ts
Use `document.documentElement.offsetHeight` instead of `document.documentElement.scrollHeight`.
When the node is removed, `scrollHeight` doesn’t change, and iframe height stays the same, because in the web app the iframe is stretched to 100% of the container that has the height based off the last iframe size.
=> feat: use offsetHeight for canvasGeometry [SPA-2804]

package-lock.json, packages/core/src/entity/EntityStoreBase.spec.ts, packages/core/src/entity/EntityStoreBase.ts, packages/test-apps/react-vite/src/components/ComponentUsingReferences/ComponentUsingReferences.tsx
A customer noticed that assets stopped rendering when another component on the experience used the recently added L2 resolution of reference fields.
As soon a registered component uses the `'Link'` variable type, the SDK receives entities with the reference fields not being links but actual entities already.
When resolving deep bindings (for assets), the entity store is now able to handle this scenario as well. I added a test that also showcases this scenario.
=> fix(core): deep binding resolution with reference field already being a resolve entity [SPA-2843]

package-lock.json, packages/core/src/utils/debugLogger.ts
When using the Brave browser, activating the deprecated flag `#block-all-cookies-toggle` and toggling on the legacy option "Block all cookies", a check like `typeof localStorage` will throw an error. While logic like `typeof asdf` will gracefully return `undefined`, the browser seems to even punish the this check with an error.
**Background to this flag:**
It "broke the web" for users as the aggressive behavior would cause several issues on web page with Studio just being yet another anecdote that proves it.
- https://github.com/brave/brave-browser/issues/42061
- https://github.com/brave/brave-browser/wiki/Block-all-cookies-global-Shields-setting
Moving the `typeof localStorage` check inside the try-catch-block will also handle this case gracefully from now on.
=> fix(core): move typeof localStorage check into try catch block to support aggressive cookie settings in Brave [SPA-2838]

package-lock.json, packages/core/src/utils/styleUtils/index.ts, packages/core/src/utils/styleUtils/ssrStyles.spec.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/core/src/utils/styleUtils/toMediaQuery.spec.ts, packages/core/src/utils/styleUtils/toMediaQuery.ts, packages/core/src/utils/transformers/media/transformMedia.ts, packages/experience-builder-sdk/src/hooks/useMediaQuery.spec.ts, packages/experience-builder-sdk/src/hooks/useMediaQuery.ts
To fix the rendering of "mobile-only" nodes, the CSS transformation for `cfVisibility` was moved out of `buildCfStyles` and handled separately. ([PR](https://github.com/contentful/experience-builder/pull/1158))
Thanks to a customer, we learned today that this approach didn't cover SSR and instead even broke the functionality of `cfVisibility` as a whole.
To get a back control on the flow for generating media queries in CSS, all related code was moved into a separate place `toMediaQuery.ts` which conditionally accepts the `nextCondition` parameter to create negated or disjunct media queries (required for visibility rendering).
=> fix(core): consolidate CSS generation for cfVisibility in SSR and CSR [SPA-2782]

packages/core/src/entity/EntityStoreBase.ts, packages/core/src/utils/entityTypeChecks.ts, packages/core/src/utils/index.ts, packages/core/src/utils/transformers/getResolvedEntryFromLink.ts, packages/visual-editor/src/hooks/useSingleColumn.ts
We're often seeing this error: `Cannot read properties of undefined (reading 'type')`
I discovered two causes for this:
- Either the parent in `useSingleColumn` is not a "columns" node
- The entry/ asset in the EntityStore is neither an entry nor an asset (e.g. see ZEND-6498, caused by wrong JSON serialization logic)
In both cases, the page crashes, leaving little information to investigate. As it already crashes for those unexpected situations, the logic catches those now more explicit and throws an explicit error instead. The main reason seems to be having objects in the store that are neither entries nor assets which will also be addressed by [this change](https://github.com/contentful/experience-builder/commit/556fd40f7fe5c100a7b8e534df5c9b29ed9295b4).
As they are not necessary for …
=> fix(core): throw error for invalid store objects [SPA-2862]

packages/core/src/utils/transformers/getResolvedEntryFromLink.ts
When using `Link` properties in custom components, the links might not be correctly resolved depending on other `Link` properties in the same experience being populated.
Warning message that showed up in the logs:
```
Expected a link to a reference, but got: { "type":"Entry", ... }
```
So the entity store can contain entries with resolved references while `getResolvedEntryFromLink` enforced those to be links until now. I adjusted that method to gracefully accept already resolved references as well.
=> fix(core): handle entry fields being already resolved links [SPA-2863] [ZEND-6194]

packages/core/src/utils/domValues.ts, packages/visual-editor/src/components/RootRenderer/sendCanvasGeometryUpdatedMessage.ts
Don't send the nodes that has nullified bounding client rect values, as it's not rendered in the DOM.
Skip the node if its rect values are `0`.
=> feat: [] skip hidden nodes

package-lock.json, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.spec.ts, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.ts, packages/core/src/types.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/index.ts, packages/validators/src/schemas/latest.ts, packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts, packages/validators/src/types.ts, packages/validators/src/validators/tests/experienceValidator.spec.ts
Rename some pattern properties
patternPropertyDefinitions → parameterDefinitions
patternPropertyDefinitionId → parameterDefinitionId
patternProperties → parameters
Ticket: https://contentful.atlassian.net/browse/SPA-2844
=> rename patternPropertyDefinitions, patternPropertyDefinitionId, and patternProperties [SPA-2844]

packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.spec.ts, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts, packages/validators/src/validators/tests/componentSettings.spec.ts, packages/validators/src/validators/tests/experienceValidator.spec.ts
Introduce wrapping object for prebinding definitions.
⚠️ This is breaking change for pattern with prebinding enabled, but it's ok since the feature is still in development.
* Updated schema to reflect the new format and update all related code references and test fixtures to use the new format.
Before:
```
"componentSettings": {
"parameterDefinitions": {
...
},
"variableMappings": {
...
}
}
```
After:
```
"componentSettings": {
"prebindingDefinitions": [
{
"id": "$randomId",
"parameterDefinitions": {
...
},
"variableMappings": {
...
}
}
]
}
```
* Added also support for `passToNodes` and `allowedVariableOverrides` in Pattern Schema.
* Made `componentSettings`, `prebindingDefinitions` and `passToNode` objects strict.
=> refactor: add prebindingDefinitions in pattern schema [SPA-2900]

.github/workflows/vercel.yaml, examples/astrojs-ssr/README.md, examples/astrojs-ssr/astro.config.mjs, examples/astrojs-ssr/package-lock.json, examples/astrojs-ssr/package.json, examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json, examples/next-app-router/package-lock.json, examples/next-app-router/package.json, examples/next-pages-router/package-lock.json, examples/next-pages-router/package.json, package-lock.json, packages/components/rollup.config.mjs, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/rollup.config.mjs, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/visual-editor/package.json
Importing the CSS separately to improve SSR caused an error as nextjs enforced the user to import all CSS manually instead of having modules import on their own.
Previous PR: https://github.com/contentful/experience-builder/pull/1182
I tried to support a hybrid approach, i.e. per default we still load via CSS-in-JS but also offer an option to turn that off and import the CSS on your own for SSR. Generating a CSS and creating in inside JS was not easy to achieve due to https://github.com/egoist/rollup-plugin-postcss/issues/401 . After making it work with two separate rollup configs, I realized that it's not feasible to generate a function `injectGlobalStyles` that can be invoked conditionally. `inject` by postcss only allows the global injection it seems.
To fix the SDK for now, we're …
=> fix: ship CSS-in-JS instead of importing CSS for Nextjs support [SPA-2865]

packages/test-apps/react-vite/src/components/BindingToReferences/ResolveManually.tsx
As we discussed in the thread https://contentful.slack.com/archives/C01R9P3CBH7/p1747989662785529
we want to have `maybeResolveLink` available not as regular import (non-reactive), but via hook (this way it will have potential to trigger rerender and be reactive).
Originally in the [document with use case β](https://contentful.atlassian.net/wiki/spaces/PROD/pages/5469175887/Reactivity+and+Change+Detection+in+Studio+Custom+Components#%CE%B2)-Hook-useMaybeResolveLink), we looked into hook in shape of:
```
const maybeResolveLink = useMaybeResolveLink();
``` 
however, it turned out that in reality we may want to expose several methods for convenience of the user like:
this is why the proposal is for the hook to expose multiple methods:
```
const { 
maybeResolveLink,
addEntities,
hasAsset, …
```
=> fix: example of fetching maybeResolveLink via hook

packages/core/src/constants.ts, packages/core/src/utils/styleUtils/stylesUtils.spec.ts, packages/core/src/utils/styleUtils/stylesUtils.ts, packages/storybook-addon/src/components/StyleSectionComponents/SizeInput/SizeSelector.tsx, packages/test-apps/nextjs/src/components/CustomImageComponent.tsx, packages/test-apps/react-vite/src/components/CustomImageComponent.tsx, packages/visual-editor/src/components/EditorBlock/useComponentProps.ts
In the new editor, one could not click on an empty carousel or custom image.
1. The carousel had no minimum size anymore. I fixed that by adding a rule that every custom component that accepts children get's a minimum height and width of `80px` (like before). This might not work in some specific use cases but it follows the existing behaviour and also it doesn't affect preview/delivery.
2. The custom image in our test apps did not correctly forward the HTML attributes to identify nodes in the DOM. Added that
=> fix: clickable carousel and custom image [SPA-2945]

examples/astrojs-ssr/package-lock.json, examples/astrojs-ssr/package.json, examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json, examples/next-app-router/package-lock.json, examples/next-app-router/package.json, examples/next-pages-router/package-lock.json, examples/next-pages-router/package.json
Bump SDK version to latest v1 version in all example apps.
Tested both in editor mode and delivery with a medium complexity experience and didn't see any issues.
https://contentful.atlassian.net/browse/SPA-2943
=> chore: bump SDK to latest v1 version in all example apps [SPA-2943]

packages/visual-editor/src/components/RootRenderer/useCanvasGeometryUpdates.ts
Send initial canvas geometry when the tree is not yet received or is empty, so the web app can render the canvas height properly.
Send geometry immediately after creating a mutation observer.
=> chore: [] send initial canvas geometry

packages/components/src/components/Image/Image.css, packages/components/src/components/Image/Image.tsx
This PR aims to solve two issues with images:
- Safari & Firefox showing native missing image indicators on top of our image placeholder
- "Corner radius" property not being reflected in image placeholder when no image is bound / when building a pattern
- Replaced existing hard-coded base64 image used in placeholder image with a cross-browser supported base64 string for a 1x1 pixel svg
- Moved placeholder image outline styles to wrapper `div` and applied `overflow: hidden` to ensure the `border-radius` value is visually reflected
| Before | After |
|--------|--------|
| <img width="2718" height="1322" alt="CleanShot 2025-07-29 at 14 20 57@2x" src="https://github.com/user-attachments/assets/c30f6c9d-2e82-4c33-b154-cae2b44fc81c" /> | <img width="2718" height="1322" alt="CleanShot 2025-07-29 …
=> fix: avoid native missing image indicator cross-browser & show corner radius on placeholder image

packages/visual-editor/src/components/EditorBlock/useComponentProps.ts
As part of #1158, we had to change the way we render `cfVisibility` to not override custom display values for visible nodes.
Due to a faulty merge conflict resolution, the visibility was not rendered at all in editor mode for v3.
Turn this prop also in CSS - we have to do it explicitly but at least, it's only one function call.
=> fix(visual-editor): render cfVisibility in CSS for CSR apps [SPA-2956]

packages/experience-builder-sdk/src/hooks/useDetectCanvasMode.tsx
When the iframe is rerendered for v3 in the web app, it remounts the whole thing. For _"some reason"_, the "connected" event coming from the SDK is not getting the response "requestEditorMode" and thereby reaches the handshake timeout that changes the mode to "NONE" and thereby makes the SDK fetch the experience.
This in the end leads to an error with the global entity store not being the editor one.
=> fix: increase handshake timeout for v3 switch [SPA-3058]

packages/core/src/definitions/styles.ts, packages/core/src/types.ts
A customer has reported that the cfTextAlign setting is not compatible with Right to Left languages, as it uses left/right instead of start/end. 
Here is the link to the video:
https://www.loom.com/share/66039cd623e243509754a7f94025b080?sid=fd41560d-6657-4fd5-a123-d397f038ae68 
We switched to using logical alignment values (start, center, end) to ensure proper text alignment across different writing systems. Unlike left and right, which are fixed, start and end adapt based on the text direction (ltr or rtl). This allows us to support both left-to-right (e.g., English) and right-to-left (e.g., Arabic) languages with a single consistent alignment system, improving internationalization support without hardcoding language-specific rules.
=> fix: text align validation from left right to start end [SPA-3060]

packages/core/src/types.ts, packages/visual-editor/src/components/RootRenderer/sendCanvasGeometryUpdatedMessage.ts, packages/visual-editor/src/components/RootRenderer/useCanvasGeometryUpdates.ts
Don't wait for all images to be loaded before sending the canvas geometry, as some images might be never loaded due to lazy loading.
1. Keep sending canvas geometry on dom mutation, but without waiting for images
2. Collect all images on dom mutation, as new images can be added asynchronously
3. Wait for each image to be loaded separately to send a new geometry update, as they can shift the layout
1. To validate the idea that lazy images prevent sending geometry update I added a lazy image that is not visible
2. Removing the promise that waits for all images makes it send the geometry correctly
3. After the lazy image is loaded (e.g. it's scrolled into view), the handler for this message correctly updates the geometry
=> fix: [SPA-3075] send canvas geometry on image load separately

packages/core/src/constants.ts, packages/core/src/types.ts, packages/visual-editor/src/components/RootRenderer/useCanvasGeometryUpdates.ts
If the interaction layer of canvas is disabled, the iframe intercepts the wheel event, on which web app relies on to handle pan and zoom.
Send the data from wheel event back to the web app so it can handle pan and zoom properly.
=> feat: [] prepare SDK to delegate pan to the canvas

package-lock.json, packages/components/src/components/Divider/ContentfulDivider.tsx, packages/core/src/types.ts, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/experience-builder-sdk/src/utils/withComponentWrapper.spec.tsx, packages/experience-builder-sdk/src/utils/withComponentWrapper.tsx, packages/test-apps/react-vite/src/studio-config.ts, packages/visual-editor/package.json
After removing the dragging wrapper, another wrapper logic remains that is added during registration (`withComponentWrapper`). Unfortunately, we realized only now that by default, we add the wrapping container to every registered component, and changing that would be a breaking change as every component would have to forward HTMK attributes like `data-cf-node-id`.
Background for the research was a component in our demo applications, which was not clickable. It is registered together with a `wrapContainer`, which caused a bug: With the new DND system, we don't need a `ref` anymore, but instead fully rely on every component to render the attribute `data-cf-node-id` to calculate its coordinates. The wrapping logic didn't render those anymore (it did in [the …
=> fix: support for wrapComponent and adding deprecation notices [SPA-3087]

packages/core/src/__fixtures__/breakpoints.ts, packages/core/src/registries/breakpointsRegistry.spec.ts, packages/core/src/utils/breakpoints.spec.ts, packages/core/src/utils/breakpoints.ts, packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/validators/tests/componentTree.spec.ts, packages/validators/src/validators/tests/validateBreakpointDefinitions.spec.ts
To enable our customers build mobile-first websites, the validation is updated to allow using a "mobile-first" strategy, meaning that you can define a list of breakpoint definitions with strictly increasing queries.
Example
```
defineBreakpoints([
{
id: 'test-mobile',
query: '*',
displayName: 'All Sizes',
displayIcon: 'mobile',
previewSize: '350px',
},
{
id: 'test-tablet',
query: '>576px',
displayName: 'Tablet',
displayIcon: 'tablet',
previewSize: '820px',
},
{
id: 'test-desktop',
query: '>982px',
displayName: 'Desktop',
displayIcon: 'desktop',
previewSize: '1080px',
},
{
id: 'test-large-screen',
query: '>1200px',
displayName: 'Large Screen',
displayIcon: 'desktop',
previewSize: '100%',
},
]);
```
https://github.com/user-attachments/assets/db00ac2b-c750-43fa-b6b5-ca0815bf2435
=> feat: allow mobile-first breakpoint definitions [SPA-3041]

.eslintrc.cjs, package-lock.json, package.json, packages/core/package.json, packages/core/src/entity/EntityStoreBase.ts, packages/core/src/utils/localizeEntity.ts, packages/core/src/utils/transformers/transformRichText.ts
Some customer's end users have to use old browser versions (like Chrome v91). So we can't safely use APIs that are not supported in those version without breaking a customer's site for such users.
Introduce an `eslint-plugin-compat`, to prevent using such APIs without guarding in the packages that run in production.
So far this change has only affected `structuredClone`, that I'm replacing with `cloneDeep` from `lodash-es`.
=> fix: prevent using some browser APIs unsupported in old versions [ZEND-6795]

packages/visual-editor/src/components/RootRenderer/RootRenderer.module.css, packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx
To achieve complete parity between editor and preview mode, and allow having experiences without `divs`, we drop the root node of the experience in editor mode.
=> fix: remove editor wrapper [SPA-3197]

packages/validators/src/schemas/v2023_09_28/common.ts
Support optional `prebindingId` on ComponentTree node.
https://contentful.atlassian.net/browse/SPA-3184
=> Feat: support prebindingId on component tree node [SPA-3184]

packages/components/src/components/Columns/SingleColumn.tsx, packages/components/src/components/ContentfulContainer/ContentfulContainer.tsx, packages/components/src/types.ts, packages/components/src/utils/extractRenderProps.ts, packages/core/src/types.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts, packages/visual-editor/src/components/EditorBlock/useComponentProps.ts
Based on the feedback for #1291, I filed another PR to revisit the shape of the new registry options.
Replacing the complex object `node` with `isEmpty` and `nodeBlockId` as we only need those internally and the shape of `node` could change at some point, causing a breaking change otherwise.
Defining a component:
```ts
defineComponents([{
component: MyComponent
definition: myComponentDefinition,
options: {
enableEditorProperties: {
isEditorMode: true,
isEmpty: true,
},
},
}])
```
Using it:
```ts
type MyComponentProps = EditorProperties<'isEditorMode' | 'isEmpty'> & {
myValue: string;
}
export const MyComponent = (props: MyComponentProps) => {
// ...
}
```
=> feat: replace node editorProp with isEmpty and nodeBlocKId

packages/core/src/types.ts
Adds prebindingId in the ExperienceTreeNode['data'] type.
=> fix: add prebindingId to the ExperienceTreeNode type [SPA-3184]

packages/visual-editor/src/components/EditorBlock/useComponentProps.ts
While defining a custom component, the developer could define a property to override our internal ones, e.g. `data-cf-node-id` (which would break the editing experience).
To protect any reserved properties, they get a high priority during the object destruction in `useComponentProps`
=> fix: deny overwriting internal properties by custom ones [SPA-3210]

packages/core/src/types.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/componentRegistry.ts
So far, the SDK allowed customers to overwrite built-in components, including the very basic structural ones. It is already possible to remove support properties from it or change other parts of its definition. However, so far the preview mode would always render the built-in `ContentfulContainer` causing a mismatch between editor and preview mode and giving the impression that this is supported.
As we learned from customers that they want to exploit this, we want to open this last protection and let them render any React component, replacing the built-in ones.
Since those components are tied to our protocol and internal behaviour, we foresee that at some point, we might apply changes to those components. If customers already use their own custom solutions, this could lead to unexpected …
=> feat: introduce SDK option to enable full structure overwrites [SPA-3198]

packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/visual-editor/src/components/EditorBlock/EditorBlock.tsx
If the user defined a custom property `children`, it should be passed through to their custom component.
Only if the component accepts true child nodes (`children: true`) and it's a non-empty list, they will take precedence over that custom property.
After having a look at the type of `React.createElement`, I learned that `children` should be passed as [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) (`...children`). I worked probably this way because React can now render multiple nodes on the top-level of one render call ([added in React 16.0](https://legacy.reactjs.org/blog/2017/09/26/react-v16.0.html)).
This is a regression of the change I did [here](https://github.com/contentful/experience-builder/pull/1275/files#diff-e801c2 …
=> fix: allow passing children property if there are no children [SPA-3210]

packages/visual-editor/src/utils/checkIsNodeVisible.spec.ts, packages/visual-editor/src/utils/checkIsNodeVisible.ts
When changing breakpoint IDs and thereby causing `cfVisibility` to become `undefined`, the editor wouldn't render those nodes as the pre-check in `checkIsNodeVisible` would treat `undefined` as false while the actual rendering mechanics don't actively hide it in that case.
Check explicitly for `false` values in `cfVisibility` to treat `undefined` as truthy.
=> fix: treat undefined cfVisibility as true in editor [SPA-3216]

packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/validators/tests/componentTree.spec.ts
* Add validation to make sure that `parameters` and `prebindingId` appear always as a pair in component tree nodes.
* Parameters can be an empty object in case a pattern instance has prebinding configured but not source has been selected yet.
=> feat: add validations for pre-binding attributes in component tree nodes [SPA-3201]

packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/validators/tests/componentTree.spec.ts
Revert of revert contentful/experience-builder#1334.
Bring back prebinding validations now that UI is adjusted to respect them: https://github.com/contentful/experience-builder/pull/1328
=> Revert "Revert "feat: add validations for pre-binding attributes in component tree nodes [SPA-3201]""

packages/test-apps/react-vite/src/Page.tsx
When working with the test app, we always want to have the debug mode enabled.
=> fix: enable debug mode per default for react-vite test app []

packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/validators/tests/componentTree.spec.ts
* Add validation for Experiences to ensure that when `prebindingId` is present, `parameters` are also present.
* We don't throw an error if `parameters` are present but `prebindingId` is not as older experiences were always including `parameters: {}`.
https://contentful.atlassian.net/browse/SPA-3285
=> fix: add experience prebiding validations [SPA-3285]

packages/experience-builder-sdk/src/core/sdkFeatures.ts
* Adds `hasPrebinding` feature in the SDK, to prevent SDK versions that don't support it to have prebinding available.
* Needs to be merged/released together or after #1326 
https://contentful.atlassian.net/browse/SPA-3262
=> fix: prebinding sdk feature [SPA-3262]
