contentful/experience-builder

src/blocks/VisualEditorContext.tsx, src/styles/VisualEditorRoot.css
- Add height and overflow to visual editor root
- Add capture to scroll event so that nested element scrolls can be bubbled up
=> feat: consistent sizing across options [SPA-1463]

src/blocks/EmptyEdtorContainer.tsx, src/styles/EmptyContainer.css, src/styles/variables.css
=> style: fix the issue with the width of the empty container []

src/blocks/transformers.ts, src/core/stylesUtils.ts, src/styles/ContentfulContainer.css
- Use border-box sizing for container components
- Adapt container width to margins
=> fix: adapt container to margins and paddings [SPA-1523]

README.md
- Added read me file to root level
=> chore: added read me file [SPA-1395]

packages/experience-builder-sdk/.gitignore, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/sdkVersion.ts
=> chore: remove sdkVersion file from git to fix lerna publish flow

packages/experience-builder-sdk/src/blocks/editor/VisualEditorContext.tsx, packages/experience-builder-sdk/src/communication/sendHoveredComponentCoordinates.ts, packages/experience-builder-types/src/constants.ts
Supports: https://github.com/contentful/user_interface/pull/18364
* Don't send tree together with DesignComponentAdded event
* Declare default design component category as a constant
* Remove some unused event types and code
=> feat: add new constant and remove unused variables [SPA-1605]

README.md
=> fix!: testing breaking change impact on version of prerelease

.github/workflows/main.yml
I believe by adding this we will then be able to manually call our complete github actions from within a feature branch
Source: https://github.com/orgs/community/discussions/25746#discussioncomment-3249056
=> chore: create main.yml

packages/experience-builder-sdk/src/communication/MouseOverHandler.ts
`display:contents` leads to having no "box" in the actual DOM as somehow mentioned [here](https://drafts.csswg.org/css-display/#transformations) and [here](https://dev.to/ben/how-would-you-go-about-detecting-the-height-of-content-within-an-iframe-14d8#comment-f17j).
Thus, it fails to calculate any bounding client rect for this node. As a work around we calculate the size of each child and add them up.
=> fix: calculate component client rect via children [SPA-1652]

packages/core/src/definitions/styles.ts, packages/core/src/registries/designTokenRegistry.ts, packages/core/src/utils/breakpoints.ts
=> feat: add cfBorder designTokens resolver [ALT-208]

packages/experience-builder-sdk/src/index.ts
=> fix(experience-builder-sdk): export ComponentDefintion [ALT-266]

packages/components/src/components/ContentfulContainer/ContentfulContainer.tsx, packages/visual-editor/src/hooks/useComponent.tsx
=> fix: use proper exported type in ContentfulContainer [SPA-1775]

packages/components/src/components/ContentfulContainer/ContentfulContainer.tsx, packages/components/src/components/ContentfulContainer/ContentfulContainerAsHyperlink.tsx, packages/experience-builder-sdk/src/components/ContentfulContainerAsHyperlink.tsx, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/src/hooks/usePlaceholderStyle.ts, packages/visual-editor/src/store/tree.ts, packages/visual-editor/src/types/treeActions.ts, packages/visual-editor/src/utils/getTreeDiff.ts, packages/visual-editor/src/utils/treeHelpers.ts
This release among others fixes the rendering logic for assemblies
=> release@next

packages/visual-editor/src/components/Draggable/DraggableChildComponent.tsx, packages/visual-editor/src/components/Draggable/DraggableComponent.tsx, packages/visual-editor/src/components/Dropzone/useComponentProps.ts
I didn't catch these types issues before merging #296
=> fix: types in visual editor []

packages/core/src/definitions/styles.ts, packages/storybook-addon/src/components/StyleSectionComponents/BorderInput/useBorderConstituents.ts, packages/storybook-addon/src/utils/variables.ts
=> fix: border default setting now produces a 1px solid black border [ALT-403]

packages/visual-editor/src/components/Dropzone/useComponentProps.ts
When an assembly contains more than one top-level container, those should be aligned vertically. Due to the DND-related element that wraps each assembly instance, they are instead positioned horizontally.
While it's not the best solution, it works well rendering an assembly instance with `block` instead of `flex` and ensuring that the wrapper itself fills the whole width as the `assembly` node doesn't define an explicit width - it uses `display: contents` instead to forward the children styles (and pretend like it doesn't "exist").
Especially for the case of using an assembly instance inside a column, the height calculation would break as each top-level container/section inside the assembly defines `height: 100%` per default. To avoid these sizing bugs, we need to set the `height` to the …
=> fix: wrap assembly with correct container styles [SPA-1869]

packages/core/src/constants.ts, packages/visual-editor/src/components/Dropzone/EditorBlockClone.tsx, packages/visual-editor/src/components/RootRenderer/DNDProvider.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/src/utils/simulateMouseEvent.ts
See related user_interface PR for description and sample video:
https://github.com/contentful/user_interface/pull/20078
=> fix(canvas-interactions): proper handling of reparenting off canvas [ALT-412]

packages/core/src/entity/EntityStore.ts
Serialize entry and asset references with JSON.stringify()
Introduced toJSON function in EntityStore class
=> feat: added toJSON function in entity store [SPA-1884]

packages/visual-editor/src/components/Dropzone/styles.module.css
Based on the collab during Team Altitude's stand up, we decided to update dropzone indicator colors to the following.
=> fix(canvas-interactions): update dropzone indicator colors

packages/core/src/definitions/styles.ts
Small follow up PR related to https://github.com/contentful/user_interface/pull/20219 and fixes https://contentful.atlassian.net/jira/software/c/projects/ALT/boards/1552
=> fix(components): change default of structure component margins to 0 [ALT-519]

packages/core/src/entity/EntityStore.ts, packages/core/src/entity/EntityStoreBase.ts
=> fix: adding tojson to base class [SPA-1884]

packages/visual-editor/src/components/Dropzone/EditorBlock.tsx, packages/visual-editor/src/components/VisualEditorRoot.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts, packages/visual-editor/src/store/entityStore.ts, packages/visual-editor/src/types/constants.ts
=> Release @next

.github/workflows/main.yml, .github/workflows/publish.yaml
Removing references to the `media-asset-changes` feature branch - this branch was merged in #397
=> chore: clean up workflows

package-lock.json, packages/storybook-addon/package.json
Updates dependencies in the Storybook plugin to ensure it works with the latest version of the Experiences SDK.
Note
(Not fully tested to work with Storybook v8, only made to work with v7)
=> fix(storybook-plugin): working with the latest SDK on storybook v7 [ALT-652]

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/visual-editor/src/components/Dropzone/useComponentProps.ts
Add the hyperlink value to the schema for the content-api to be ready to accept these values
=> feat: [SPA-1774] add hyperlink value to schema

CHANGELOG.md, lerna.json, package-lock.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/components/src/components/RichText/RichText.css, packages/components/src/components/RichText/RichText.cy.tsx, packages/components/src/components/RichText/RichText.tsx, packages/core/CHANGELOG.md, packages/core/package.json, packages/experience-builder-sdk/CHANGELOG.md, packages/experience-builder-sdk/package.json, packages/validators/CHANGELOG.md, packages/validators/package.json, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/visual-editor/CHANGELOG.md, packages/visual-editor/package.json, packages/visual-editor/src/communication/sendSelectedComponentCoordinates.ts, packages/visual-editor/src/components/Dropzone/useComponentProps.ts
* fix(components): rich text formatting [ALT-585] (#533)
* fix(components): rich text formatting [ALT-585]
* fix: tests
* feat: [SPA-1774] add hyperlink value to schema (#540)
* feat: add hyperlink value to schema
* fix: adjust fallback for props
* fix(visual-editor): select component when image loads [ALT-646] (#537)
---------
[ALT-585]: https://contentful.atlassian.net/browse/ALT-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALT-585]: https://contentful.atlassian.net/browse/ALT-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SPA-1774]: https://contentful.atlassian.net/browse/SPA-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALT-646]: …
=> Release@main

CHANGELOG.md, lerna.json, package-lock.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/components/src/components/RichText/RichText.css, packages/components/src/components/RichText/RichText.cy.tsx, packages/components/src/components/RichText/RichText.tsx, packages/core/CHANGELOG.md, packages/core/package.json, packages/experience-builder-sdk/CHANGELOG.md, packages/experience-builder-sdk/package.json, packages/validators/CHANGELOG.md, packages/validators/package.json, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/visual-editor/CHANGELOG.md, packages/visual-editor/package.json, packages/visual-editor/src/communication/sendSelectedComponentCoordinates.ts, packages/visual-editor/src/components/Dropzone/useComponentProps.ts
=> merge next

packages/core/src/test/__fixtures__/composition.ts, packages/experience-builder-sdk/src/blocks/preview/PreviewDeliveryRoot.test.tsx, packages/experience-builder-sdk/src/blocks/preview/PreviewDeliveryRoot.tsx, packages/experience-builder-sdk/src/constants.ts, packages/experience-builder-sdk/test/__fixtures__/composition.ts, packages/validators/src/schemas/schemaVersions.ts
Remove unsupported schema versions from `SchemaVersions` schema/type.
=> chore: remove oudated schema versions [SPA-1790]

packages/validators/src/schemas/componentDefinition.ts, packages/validators/test/validator.spec.ts
Adjust validators for hyperlink feature
Three important notes on Pull Requests:
- In general, you should ask yourself whether this code change will improve or worsen the overall code quality. Any new tech debt will probably never be cleaned up.
- Please remember that newly introduced logic should be validated and protected through testing.
- Take a look at PR guides such as Google's [Google’s Code Review Guidelines](https://google.github.io/eng-practices/) and [Blockly - Writing a Good Pull Request](https://developers.google.com/blockly/guides/contribute/get-started/write_a_good_pr)
-->
=> feat: [SPA-1774] add hyperlink to component definition

packages/components/src/components/Button/index.ts
Make our button component prop url also from type hyperlink
=> refactor: [] make button url hyperlink type

packages/core/src/types.ts, packages/test-app/src/eb-config.ts
Mini PR to add typings to core for layer renaming
Ticket: https://contentful.atlassian.net/browse/ALT-776
=> feat(experiences): implement layer renaming [ALT-776]

packages/visual-editor/README.md
Add github documentation for the visual editor package
=> [ALT-817-visual] Add github documentation for the visual editor package

packages/experience-builder-sdk/README.md
Add github documentation for the sdk package
=> [ALT-817-sdk] feat: add github documentation for the sdk package

packages/validators/README.md
Add documentation for @experiences/validators package
=> docs: update documentation for validators package

packages/components/rollup.config.mjs
=> chore: remove json assert method for node v22 compatibility

packages/experience-builder-sdk/src/core/sdkFeatures.ts
Added a SDK Version UI feature flag
=> feat: add sdk ui version has available feature

packages/validators/src/schemas/v2023_09_28/experience.ts, packages/validators/test/v2023_09_28/experienceValidator.spec.ts
Update breakpoint display icon property
=> chore: update breakpoint display icon property []

packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/visual-editor/src/utils/assemblyUtils.ts
Fixes the multiple slots functionality to work inside patterns.
Ticket: https://contentful.atlassian.net/browse/ALT-927
https://github.com/contentful/user_interface/assets/8539634/b1c9ba56-4579-4d84-bf7d-9f17aa4bc451
=> fix: experiences patterns slots

packages/test-app/src/eb-config.ts
Change up the custom icons for the test-app
Ticket: https://contentful.atlassian.net/browse/ALT-953
=> feat(test-app): change custom component icons [ALT-953]

packages/core/src/communication/sendMessage.ts, packages/core/src/constants.ts, packages/core/src/types.ts, packages/core/src/utils/validations.ts, packages/experience-builder-sdk/src/hooks/useDetectEditorMode.tsx, packages/visual-editor/src/communication/onComponentDrop.ts, packages/visual-editor/src/communication/sendSelectedComponentCoordinates.ts, packages/visual-editor/src/components/RootRenderer/DNDProvider.tsx, packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx, packages/visual-editor/src/hooks/useEditorSubscriber.ts
Add types for messages exchanged between SDK and Wep app.
=> fix: add TS types for messages exchanged between SDK and Web app [SPA-2122]

.github/workflows/check.yaml, .github/workflows/main.yml, .github/workflows/pact-record-release.yaml, .gitignore, package-lock.json, packages/visual-editor/package.json, packages/visual-editor/src/hooks/useEditorSubscriber.spec.ts, packages/visual-editor/test/__fixtures__/entities.ts
We want to leverage PactFlow for our new contract tests between UserInterface and ExperiencesSDK. This PR introduces a first consumer test and integrates the pact integration into our GitHub actions.
- Add a unit test that creates a pact for an SDK message received from the UserInterface ("updatedEntity"). The test not only defines the payload shape but also tests the subsequent behavior of the message listener.
- Add a GH workflow step to push the pact to PactFlow.
- Persist generated pact as an artifact in the workflow.
- Add a GH workflow step that records the published pact as released when being on the main branch.
- Deactivate both steps via a repository variable `ENABLE_PACTFLOW` until the procurement for the tool is successful.
- Create a system account in PactFlow with permission …
=> chore: add pact consumer test and publish to provider [SPA-2123]

.github/workflows/publish.yaml
Trying to publish the updated CLI tool directly to NPM as a public package
=> chore: changing publish action for publishing the CLI tool to NPM []

.github/workflows/publish.yaml
Another attempt to get Action config able to publish CLI tool to NPM as a public package
=> chore: update publish script to publish CLI tool to NPM []

package-lock.json, packages/experience-builder-sdk/src/hooks/useDetectEditorMode.tsx, packages/experience-builder-sdk/src/index.ts
Prevent this error from being thrown when running the nextjs test app:
=> fix: useDetectEditorMode throws an error in the nextjs test app []

package-lock.json, packages/core/src/registries/designTokenRegistry.ts, packages/core/src/types.ts
- Add text style work behind sidebar redesign FF
- shows text style if sidebar redesign feature flag is on and user has text tokens defined
- font color, size, line height, and line spacing values change if a text style is selected
[] merge backend changes
https://www.loom.com/share/6988c3976055421fa981494740616c8a?sid=ae60ad9c-b64b-4bf5-a90d-fc93d5a1b9ad
=> [ALT-967] fix: Move Text Style work behind sidebar redesign FF

packages/core/src/fetchers/createExperience.spec.ts, packages/core/src/fetchers/createExperience.ts, packages/core/src/fetchers/fetchById.ts, packages/core/src/fetchers/fetchBySlug.ts, packages/core/src/types.ts, packages/core/src/utils/index.ts, packages/core/src/utils/supportedModes.ts, packages/experience-builder-sdk/src/index.ts
=> remove deprecated InternalSDKMode & ExternalSDKMode types

packages/core/src/constants.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/core/src/utils/styleUtils/styleTransformers.ts, packages/core/src/utils/styleUtils/stylesUtils.ts, packages/visual-editor/src/hooks/useComponentProps.ts
Add `cfVisibility` to the set of CF-controlled attributes and translate it to CSS using `display: none`.
=> feat: introduce rendering cfVisibility in SDK

packages/core/src/utils/index.ts, packages/core/src/utils/patternUtils.spec.ts, packages/core/src/utils/patternUtils.ts, packages/visual-editor/src/utils/assemblyUtils.spec.ts, packages/visual-editor/src/utils/assemblyUtils.ts
We will be using this similar piece of code in user interface as well. So better to not repeat the code.
=> feat: export deserialize pattern node variables from core package [SPA-2376]

package-lock.json, packages/templates/nextjs-marketing-demo/package.json, packages/templates/nextjs-marketing-demo/src/app/globals.css, packages/templates/nextjs-marketing-demo/src/app/layout.tsx, packages/templates/nextjs-marketing-demo/src/components/ButtonComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/components/Icon.tsx, packages/templates/nextjs-marketing-demo/src/studio-config.ts
Adds the Ant component lib to the marketing demo app and a button component.
=> feat: add ant component lib and button component [ALT-1241] [ALT-1244]

package-lock.json, packages/core/src/utils/components.ts, packages/visual-editor/src/components/DraggableBlock/Dropzone.tsx
[UI PR](https://github.com/contentful/user_interface/pull/23459)
Update `isComponentAllowedOnRoot` function check if the component is a pattern since patterns are allowed at the root level.
https://www.loom.com/share/0ef10aa4b61241308fd88f9cece97e7f?sid=58cc9344-2b6f-4057-9ad6-d4712c6f29ac
=> [ALT-1202] fix: isComponentAllowedOnRoot logic to allow patterns to be reparented at the root level

packages/core/src/fetchers/fetchAllEntities.spec.ts, packages/core/src/fetchers/fetchAllEntities.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/fetchers.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
This reverts commit e475e62eb7fdee66e36b52c4a3076cb9503a9918.
Issues popped up with deeply bound images. Will revert this fix and look for a permanent fix for the original issue.
=> fix: Revert "fix: resolve fetched entities for experiences [ALT-1146] (#754)"

packages/templates/nextjs-marketing-demo/src/components/CardComponentRegistration.tsx, packages/templates/nextjs-marketing-demo/src/components/layout/Header.tsx, packages/templates/nextjs-marketing-demo/src/components/layout/Nav.tsx, packages/templates/nextjs-marketing-demo/src/components/layout/header.module.css, packages/templates/nextjs-marketing-demo/src/components/layout/nav.module.css
Hides the header navigation on mobile breakpoint for the marketing demo app
https://github.com/user-attachments/assets/cd017b7c-46b1-4336-a9da-45ce563aa142
=> feat: hide nav on mobile in marketing demo app [ALT-1295]

packages/core/src/registries/designTokenRegistry.ts
Fix design token so that having keys spaces/multiple words are allowed 
https://www.loom.com/share/810d668315ed42f3bce7820d327874e4?sid=4d2728be-4cba-4e9a-b85e-66aee828eeb7
DT defn:
```
const color = {
'Slate dark': '#94a3b8',
Azure: 'azure',
Orange: 'var(--cf-color-orange)',
Blue: '#0000ff',
Red: '#ff0000',
Green: '#00ff00',
};
// register design tokens
defineDesignTokens({
spacing: { 'X S s': '4px', S: '16px', M: '32px', L: '64px', 'X L XL': '128px' },
sizing: { 'X S SS': '16px', S: '100px', M: '300px', L: '600px', 'X L XL': '1024px' },
color: color,
border: {
Azure: { width: '11px', style: 'solid', color: color.Azure },
Hero: { width: '12px', style: 'dashed', color: color.Orange },
Card: { width: '11px', style: 'solid', color: color.Blue },
Carousel: { width: '12px', style: 'dotted', …
```
=> fix: update design token breakpoint parsing logic to work with spaced out dt keys

packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts
Prevent elements with a percentage height/width from resizing when being moved on the canvas.
Currently when you drag an element that has a percentage height/width, such as an Image component with 100% height, the height of the component grows to the full height of the iframe as soon as it's picked up for dragging.
With this change, I pulled in existing state from the `draggedItem` store into `useComponentProps`, and made it so we will set a `maxHeight` and/or `maxWidth` on the dragging element so that it stays the same size that it was on the canvas when it was first picked up.
This video demonstrates that no matter what the relative size of the component on the canvas is, when it is picked up for dragging to a new location, the dragged component no longer resizes when its picked up: …
=> fix(visual-editor): prevent elements from resizing on drag [ALT-1371]

packages/experience-builder-sdk/src/core/sdkFeatures.ts
Version history fails on older versions. So we are restricting it to only current
=> chore: adds version history as a feature LUMOS-388

packages/core/src/entity/EditorEntityStore.ts, packages/core/src/entity/EditorModeEntityStore.ts, packages/visual-editor/src/components/DraggableBlock/EditorBlock.tsx, packages/visual-editor/src/hooks/useComponent.tsx, packages/visual-editor/src/hooks/useComponentProps.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts
Allow to render patterns recursively. Support has been added for the editor mode only.
1. **For now only works in editor mode**
2. **Binding, design values over-writes are not functioning properly**
=> feat: enable recursive pattern rendering [SPA-2434]

packages/test-apps/react-vite/src/styles.css
Change the react-vite test app to use sans-serif font.
=> chore: switch vite test app to use sans-serif font []

packages/core/src/types.ts, packages/test-apps/nextjs/src/studio-config.ts, packages/test-apps/react-vite/src/studio-config.ts
add an experimental components option to options in define components
https://contentful.atlassian.net/jira/software/c/projects/ALT/boards/1552?selectedIssue=ALT-1413
=> feat: add experimental components to define components

packages/experience-builder-sdk/src/ExperienceRoot.tsx
=> fix: small clean up in ExperienceRoot

packages/templates/nextjs-marketing-demo/src/middleware.ts
=> chore: change locale code for german to 'de-DE' [ALT-1383]

packages/visual-editor/src/hooks/useComponent.tsx
Pass in isExpEditorMode as a prop to rendered components
https://github.com/user-attachments/assets/7b8739cf-5302-45c7-bf4e-b81f2e7d5228
=> [ALT-1459] feat: add is in experiences editor mode boolean to component when dropped onto the canvas

packages/core/src/entity/EntityStore.ts, packages/core/src/fetchers/fetchExperienceEntry.spec.ts, packages/core/src/fetchers/fetchExperienceEntry.ts, packages/core/src/fetchers/gatherUsedComponentsWithDeepReferences.spec.ts, packages/core/src/fetchers/gatherUsedComponentsWithDeepReferences.ts, packages/core/src/test/__fixtures__/experience.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts, packages/experience-builder-sdk/src/hooks/useFetchById.spec.ts, packages/experience-builder-sdk/src/hooks/useFetchBySlug.spec.ts
We have recently introduced nested patterns. In order to render them in preview/delivery mode we need to make some changes to our existing code. 
This PR mostly focuses on populating the used Components array with the nested patterns.
=> feat: changes required for nested patterns rendering and styles [SPA-2475]

examples/astrojs-ssr/package-lock.json, examples/astrojs-ssr/package.json, examples/astrojs-ssr/src/components/Experience.tsx, examples/next-app-router/package-lock.json, examples/next-app-router/package.json, examples/next-app-router/src/app/[locale]/[slug]/page.tsx, examples/next-app-router/tsconfig.json, examples/next-pages-router/package-lock.json, examples/next-pages-router/package.json, examples/next-pages-router/tsconfig.json, packages/test-apps/nextjs/next-env.d.ts
Updates the example apps to latest framework sdks
=> chore: update examples next15 react 19 [ALT-1449]

packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useBreakpoints.ts
Reverts contentful/experience-builder#882
=> Revert PR merge without squashing

packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useBreakpoints.ts
I rewrote the commit history to remove the previously merged PR (with force push on development branch) as I didn't use the "squash" option.
This is repeating https://github.com/contentful/experience-builder/pull/882 which already got approved by @anwaar931
=> fix: render patterns in preview [SPA-2518]

examples/astrojs-ssr/package-lock.json, examples/astrojs-ssr/package.json, examples/astrojs-ssr/src/components/Experience.tsx, examples/next-app-router/package-lock.json, examples/next-app-router/package.json, examples/next-app-router/src/app/[locale]/[slug]/page.tsx, examples/next-app-router/tsconfig.json, examples/next-pages-router/package-lock.json, examples/next-pages-router/package.json, examples/next-pages-router/tsconfig.json, lerna.json, package-lock.json, packages/components/package.json, packages/components/src/components/Button/index.ts, packages/components/src/components/RichText/index.ts, packages/components/src/components/Text/index.ts, packages/core/package.json, packages/core/src/definitions/styles.ts, packages/core/src/types.ts, packages/core/src/utils/breakpoints.ts, packages/create-contentful-studio-experiences/package.json, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/test-apps/nextjs/next-env.d.ts, packages/test-apps/nextjs/package.json, packages/validators/package.json, packages/visual-editor/package.json, packages/visual-editor/src/hooks/useBreakpoints.ts
https://github.com/contentful/experience-builder/pull/885
=> Release @main

package-lock.json
#888 didn't update the package-lock.json and as a result some builds are failing in development branch. This PR updates the package-lock accordingly.
=> fix: update package lock file

CHANGELOG.md, lerna.json, package-lock.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/create-contentful-studio-experiences/CHANGELOG.md, packages/create-contentful-studio-experiences/package.json, packages/experience-builder-sdk/CHANGELOG.md, packages/experience-builder-sdk/package.json, packages/validators/CHANGELOG.md, packages/validators/package.json, packages/visual-editor/CHANGELOG.md, packages/visual-editor/package.json
Sync next with main branch
* Checkout this branch from latest `next`
* Merge (or rebase) main
* Resolve conflicts with main
* Push
=> chore: sync next with main [ci skip]

package-lock.json, packages/create-contentful-studio-experiences/package.json
To resolve https://github.com/contentful/experience-builder/security/dependabot/107
=> chore: bump cross-spawn to 7.0.5 in create-contentful-studio-experiences package [ALT-1513]

packages/components/src/components/Image/index.ts
[JIRA Link](https://contentful.atlassian.net/browse/LUMOS-491)
=> [LUMOS-491] Change 'Alt' to 'Alt text' for image properties on default components

packages/experience-builder-sdk/src/ExperienceRoot.tsx
Reverts contentful/experience-builder#931
=> fix: Revert "fix: prevent missing components error in read only mode [LUMOS-208]" 

packages/templates/nextjs-marketing-demo/src/components/Footer/FooterNav.tsx, packages/templates/nextjs-marketing-demo/src/components/Header/HeaderNav.tsx
https://github.com/user-attachments/assets/0995f93e-0d75-42d0-8f7b-a173648df58e
=> [ALT-1544] fix: update marketing demo template app for trials so that the contact and about links are disabled

packages/experience-builder-sdk/src/utils/parseComponentProps.spec.ts
=> fix: failing test due to change in function signature

package-lock.json, packages/core/src/utils/breakpoints.spec.ts, packages/core/src/utils/breakpoints.ts, packages/core/src/utils/transformers/transformBoundContentValue.spec.ts, packages/core/src/utils/transformers/transformBoundContentValue.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.spec.tsx, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/blocks/preview/PreviewUnboundImage.tsx, packages/experience-builder-sdk/src/hooks/useBreakpoints.spec.ts, packages/experience-builder-sdk/src/hooks/useBreakpoints.ts, packages/experience-builder-sdk/src/hooks/useClassName.ts, packages/experience-builder-sdk/src/hooks/useMediaQuery.spec.ts, packages/experience-builder-sdk/src/hooks/useMediaQuery.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.spec.ts, packages/experience-builder-sdk/src/utils/parseComponentProps.ts, packages/experience-builder-sdk/test/__fixtures__/assembly.ts, packages/experience-builder-sdk/test/__fixtures__/breakpoints.ts, packages/experience-builder-sdk/test/__fixtures__/componentDefinition.ts, packages/experience-builder-sdk/test/__fixtures__/componentTreeNode.ts, packages/test-apps/nextjs/src/app/[[...slug]]/page.tsx, packages/validators/src/schemas/v2023_09_28/experience.ts, packages/visual-editor/src/hooks/useBreakpoints.spec.ts, packages/visual-editor/src/hooks/useBreakpoints.ts, packages/visual-editor/src/hooks/useComponent.spec.ts, packages/visual-editor/src/hooks/useComponentProps.spec.ts, packages/visual-editor/src/hooks/useComponentProps.ts, packages/visual-editor/src/hooks/useSingleColumn.ts
=> Release@next 

packages/core/src/types.ts, packages/validators/src/schemas/v2023_09_28/experience.ts
=> chore: add duplex thumbnail [SPA-2572]

packages/core/src/constants.ts, packages/core/src/types.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx, packages/experience-builder-sdk/src/core/preview/assemblyUtils.spec.ts, packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts
Modify rendering of assemblies to work with nested patterns.
=> feat(prebinding): render nested patterns with prebinding [LUMOS-525]

packages/experience-builder-sdk/src/ExperienceRoot.tsx
Just a typo fix to test the release process (changelog generation).
=> fix: trivial typo fix to test release process

packages/core/src/test/__fixtures__/experience.ts, packages/core/src/utils/styleUtils/ssrStyles.spec.ts, packages/core/src/utils/styleUtils/ssrStyles.ts, packages/core/src/utils/styleUtils/ssrStylesPattern.spec.ts, packages/core/src/utils/styleUtils/ssrStylesStructureComponent.spec.ts, packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx
We are adding background image optimization support in SSR, it was only supported on the CSR side. Background image optimization will add `image-set` in the CSS. 
This PR is focused on adding this support and fixing and adding new tests.
=> fix: resolve background image optimization in SSR [SPA-2698]

packages/core/src/entity/EntityStoreBase.ts
=> fix: not throw logic error if a resolved entity was detected (#1101) [ZEND-6229] 

packages/visual-editor/src/components/VisualEditorRoot.tsx
Consider the iframe horizontal scroll when sending the mouse move event while dragging an element.
https://github.com/user-attachments/assets/16b6be92-2236-4778-96dc-72e8a0b877b1
https://github.com/user-attachments/assets/462da108-c187-4b35-b031-b9502ed7336d
=> fix: consider iframe horizontal scroll when sending mouse move position [SPA-2694]

packages/visual-editor/src/components/RootRenderer/RootRenderer.tsx, packages/visual-editor/src/components/RootRenderer/useCanvasGeometryUpdates.ts
Iframe may be updated via Design tab in the web app, which affects styles only.
And in general it's more reliable to listen to the whole document for now during active development.
=> feat: listen to the entire html for canvas geometry, as there might be style changes only [SPA-2804]

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json
fixes vulnerabilities reported by the dependabot
=> chore: bump gatsby version to fix dependabot vulnerability reports [ACT-1777] [ACT-1776] [ACT-1775] [ACT-1774]

packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.spec.ts, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts
Changed the validator schema, updated the sdk packages.
=> refactor: rename defaultValue to defaultSource in prebinding [SPA-2864]

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json
=> chore: bump tar-fs to stable v in gatsby examples [ACT-1792] [ACT-1793]

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.spec.ts, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts
=> Release next

examples/gatsby/gatsby-spa/package-lock.json, examples/gatsby/gatsby-spa/package.json, examples/gatsby/gatsby-ssg/package-lock.json, examples/gatsby/gatsby-ssg/package.json, lerna.json, package-lock.json, packages/components/package.json, packages/core/package.json, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.spec.ts, packages/core/src/fetchers/attachPrebindingDefaultValueAsDataSource.ts, packages/create-studio-experiences/package.json, packages/experience-builder-sdk/package.json, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts, packages/validators/package.json, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts, packages/visual-editor/package.json
=> Release main

packages/visual-editor/src/components/RootRenderer/sendCanvasGeometryUpdatedMessage.ts
If the page have `html, body { height: 100% }` set, the height is calculated based off the default web app container height, which is 200px. 
Fallback to the `body`'s children deepest node to calculate the content height.
=> fix: [ZEND-6782] calculate 100% page size

packages/core/src/deep-binding/DeepReference.spec.ts, packages/core/src/deep-binding/DeepReference.ts, packages/core/src/utils/pathSchema.spec.ts, packages/core/src/utils/pathSchema.ts, packages/validators/src/schemas/v2023_09_28/common.ts, packages/visual-editor/src/components/EditorBlock/useComponentProps.spec.ts, packages/visual-editor/src/components/EditorBlock/useComponentProps.ts, packages/visual-editor/src/hooks/useEditorSubscriber.ts
Be able to correctly resolve prebound properties in editor mode
=> feat: handle prebinding on variables [SPA-2922]

packages/experience-builder-sdk/src/utils/withComponentWrapper.tsx
See the code comment added to `DEFAULT_OPTIONS`:
> We're use this as a default for `options`. When only one option is explicitly defined, all other default options are dropped as we're not merging the provided options with the default ones. We started merging both options with SDK v3 but many customers wouldn't upgrade as it suddenly added wrappers to their components because they only set the options to `{ wrapContainerWidth: "100%" }`. With v2, it results in `wrapComponent` being undefined but with v3, it resulted in it being `true` and thus causing unexpected layout changes. We rolled back that change to let customers migrate smoothly for now but will adjust this behaviour with v4.
When any option is provided, all other options are changed to `undefined` as that's what users rely on …
=> fix: dont merge default with defined options [SPA-3168]

package-lock.json, packages/core/src/deep-binding/DeepReference.spec.ts, packages/core/src/fetchers/fetchReferencedEntities.spec.ts, packages/core/src/fetchers/shared/sideloading.spec.ts, packages/core/src/utils/extractPrebindingData.spec.ts, packages/core/src/utils/extractPrebindingData.ts, packages/core/src/utils/styleUtils/styleTransformers.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/test-apps/react-vite/src/main.tsx, packages/validators/src/schemas/v2023_09_28/common.ts, packages/validators/src/schemas/v2023_09_28/pattern.ts, packages/validators/src/test/__fixtures__/v2023_09_28/experiencePattern.ts, packages/validators/src/validators/tests/componentSettings.spec.ts
Ticket: https://contentful.atlassian.net/browse/SPA-3223
Also added code to define design tokens for the test app, so we use more of what we support
=> feat: make passToNode mandatory in parameter definition validator [SPA-3223]

packages/experience-builder-sdk/src/utils/prebindingUtils.spec.ts, packages/experience-builder-sdk/src/utils/prebindingUtils.ts
Fixes: https://github.com/contentful/experience-builder/pull/1326#discussion_r2382784101
=> fix: handle case where CT is missing from mapping for given variable [SPA-2923]

packages/visual-editor/src/components/EditorBlock/useComponentProps.ts
=> fix[]: remove check for pre-binding info on bound value as link is always required
